### ISSUE TITLE
Saving checkpoint only on rank 0 results in future steps being out of sync

### ISSUE THREAD

**Issue by msinto93** [uber/horovod#233]
I am running Horovod multi-GPU training on a single machine with 4 GPUs.

Below is my command used to start training:

```
mpirun -np 4 \
    -H localhost:4 \
    -bind-to none -map-by slot \
    -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -mca pml ob1 -mca btl ^openib \
    python trainHorovod.py
```

As suggested in the usage instructions, I only save a checkpoint if hvd.rank() == 0. However, while the checkpoint is saving on process 0, the other processes continue to train, meaning the steps become out of sync between processes. (e.g. if I save a checkpoint at step 1000, the other processes will be at step 1005 by the time process 0 gets to step 1001). I am just checking whether this is intended behaviour or a bug in my code?

**Comment by alsrgv** [comment]
@msinto93, saving checkpoint should not result in any de-sync between workers because allreduce acts as a barrier and makes all workers wait for the slowest worker.  It sounds like you may not have added `hvd.DistributedOptimizer()` to your code and your code, in fact, does not do distributed training.

**Comment by msinto93** [comment]
This issue has now been solved, not sure exactly what was causing it but it is now working as it should. I did have hvd.DistributedOptimizer() in there. Thanks for the help.

**Comment by mrfox321** [comment]
@msinto93  Did you ever figure out what the issue was on the sync issue?
