### ISSUE TITLE
Hang on hvd.init() with multiple nodes based on Docker

### ISSUE THREAD

**Issue by jiajinyu** [uber/horovod#281]
the command I ran was
```
mpirun --allow-run-as-root -np 3 -H host1:1,host2:1,host3:1  -x NCCL_DEBUG=INFO  -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib  -mca btl_tcp_if_exclude lo,docker0  -mca plm_rsh_args "-p 12345 -i ~/.ssh/id_rsa_horovod" python /tensorflow_benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --data_format=NCHW --batch_size=64 --model=resnet50 --optimizer=momentum --variable_update=horovod --num_epochs=1 --weight_decay=1e-4 --data_dir=/datasets/imagenets/ --display_every=100
```

I print out stuff in tf_cnn_benchmarks.py and it hangs with no further output at the place calling hvd.init() in BenchmarkCNN.setup() : 
https://github.com/tensorflow/benchmarks/blob/master/scripts/tf_cnn_benchmarks/benchmark_cnn.py#L2533

I can confirm that I may ssh to host2 from host1 without any problem like this `ssh -p 12345 root@host2 -i  ~/.ssh/id_rsa_horovod`. But I can't do this the other way around. I assume this is not a problem 

This is also reproduced by running any other stuff in the example folder for multiple nodes. 
Any suggestion how to debug further would be really appreciated. Thanks.

**Comment by alsrgv** [comment]
@jiajinyu, can you connect to host3 as well?  Do you still experience this issue if you run a simple MNIST example, like in [docker instructions](https://github.com/uber/horovod/blob/master/docs/docker.md#running-on-multiple-machines)?

**Comment by jiajinyu** [comment]
@alsrgv thanks for the prompt reply. 

I can confirm I may login into host3. I am running the tensorflow_mnist.py and it still doesn't work.  Here is the command line I am using.
```
:/examples# mpirun --allow-run-as-root -np 3 -H host1:1,host2:1,host3:1  -x NCCL_DEBUG=INFO -x NCCL_SOCKET_IFNAME=^docker0  -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib  -mca btl_tcp_if_exclude lo,docker0  -mca plm_rsh_args "-p 12345 -i ~/.ssh/id_rsa_horovod" python  tensorflow_mnist.py
```

**Comment by jiajinyu** [comment]
We solved the problem be specifically setting bond0 to NCCL and MPI as the only interface.

**Comment by jageshmaharjan** [comment]
@jiajinyu , can you give a details how you solve this. What does bond0 refers to.

**Comment by qyyy** [comment]
@jiajinyu , hi man, I met the same problem as yours, can you introduce the way you solve it? How to `be specifically setting bond0 to NCCL and MPI as the only interface`?

**Comment by blythed** [comment]
There seem to be so many issues relating to this and no accepted answer. Maybe it would be good to post something in the main documentation.

**Comment by alsrgv** [comment]
@blythed, https://github.com/uber/horovod/blob/master/docs/running.md#hangs-due-to-non-routed-network-interfaces covers this issue. Do you have additional notes in mind that we could include there?

**Comment by blythed** [comment]
> @blythed, https://github.com/uber/horovod/blob/master/docs/running.md#hangs-due-to-non-routed-network-interfaces covers this issue. Do you have additional notes in mind that we could include there?

Hi alsrgv, Indeed I saw this solution, however this method did not work for me. I think when more than one network interface is available you actually need to specify which one you want. So this worked for me (whereas the answer posted didn't):

```
#!/bin/bash
mpirun -np 2 \
	-H test-1:1,localhost:1 \
	-bind-to none -map-by slot \
	-x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
	-mca pml ob1 -mca btl ^openib \
	-x NCCL_SOCKET_IFNAME=eth0 \
	-mca btl_tcp_if_exclude docker0,lo \
	python pytorch_mnist.py
```

**Comment by Vidyaranya** [comment]
> @jiajinyu , hi man, I met the same problem as yours, can you introduce the way you solve it? How to `be specifically setting bond0 to NCCL and MPI as the only interface`?

`mpirun -x NCCL_SOCKET_IFNAME=bond0 -mca btl_tcp_if_include bond0 .....` However, bond0 might not work for you. You will have to see the network interface being used by using the command `ifconfig`
