### ISSUE TITLE
Inside docker mpirun with multiple nodes cannot find libcuda

### ISSUE THREAD

**Issue by ziqifan16** [uber/horovod#313]
I am trying out horovod within docker on two machines (centos 7.3). 

On secondary worker, I run
`nvidia-docker run -it --network=host -v /mnt/nfs/var/nfs/ssh:/root/.ssh horovod:latest`
Then
`/usr/sbin/sshd -p 12345; sleep infinity"`

On primary worker, I run
`nvidia-docker run -it --network=host -v /mnt/nfs/var/nfs/ssh:/root/.ssh horovod:latest `
Then
`mpirun -np 4 -H 192.168.0.131:2,192.168.0.132:2 -mca plm_rsh_args "-p 12345" python keras_mnist_advanced.py`

Error message from the primary worker:
> ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
> Failed to load the native TensorFlow runtime.

However, if I mpirun on each node only, it can work just fine.

After diagnosis, I think the problem is when I mpirun on the secondary worker, it does not have any environment variables, such that it cannot find any needed libraries (since nvidia-smi cannot run on secondary work also).

Can anyone help on this?

**Comment by alsrgv** [comment]
@ziqifan16, are NVIDIA drivers installed on the second host?  Can you do `nvidia-smi` there?

**Comment by ziqifan16** [comment]
@alsrgv NVIDIA driver is installed on both machines (version 390.59). I can do `nvidia-smi` on both sides.

**Comment by alsrgv** [comment]
@ziqifan16, can you try adding `-x LD_LIBRARY_PATH` to your mpirun command?

**Comment by ziqifan16** [comment]
@alsrgv We solved the problem using another passwordless authentication method. Thanks.

**Comment by ziqifan16** [comment]
@alsrgv I have another problem.

Right now, I can make two dockers (in two nodes) talk to each other. But there are some nccl related problem popping out. 

Below is the error message from the primary node, any idea? Deep appreciation.

> workstation131:89:116 [0] misc/ibvwrap.cu:61 WARN Failed to open libibverbs.so[.1]
> workstation131:89:116 [0] INFO Using internal Network Socket
> workstation131:89:116 [0] INFO Using NCCL Low-latency algorithm for sizes below 16384
> Unexpected end of /proc/mounts line `overlay / overlay rw,seclabel,relatime,lowerdir=/var/lib/docker/overlay2/l/GBPMVFTVSLAMJH4HR7HN6FVDOH:/var/lib/docker/overlay2/l/XP2T2TVFTG4X5I32KG5KW6UKTD:/var/lib/docker/overlay2/l/TW4KEONK2QRTLNGAVUJN65S5MG:/var/lib/docker/overlay2/l/QEWVU73YGOPJ5A5SDNZHHCMP73:/var/lib/docker/overlay2/l/XIDN5YQSMXRPXODTEDI22TI6FG:/var/lib/docker/overlay2/l/YEDESMHJAXHNKJYG4NQNMHP43S:/var/lib/docker/overlay2/l/2U3VTYSQB75VVCT6PNGKADR6BL:/var/lib/docker/overlay2/l/VE2LQ5EN5BIUUJOR2E7OWR3MYT:/var/lib/docker/overlay2/l/BTIO'
> Unexpected end of /proc/mounts line `OT2RMHNICKTL2R67BNMFYJ:/var/lib/docker/overlay2/l/7FCIAYNUZXRBTGZGM6VWJCNZKV:/var/lib/docker/overlay2/l/AELDCCHR6WGAWVIY7SODZLN36E:/var/lib/docker/overlay2/l/ZMSTVIJPQZS3MY4ULYQALWH2EH:/var/lib/docker/overlay2/l/5L4VEVTKP37Z7MJJKHEH7L4L7Z:/var/lib/docker/overlay2/l/FUO6DB3Q73YTGDGF56YF4TT4P4:/var/lib/docker/overlay2/l/LCTHSZFTLUU47Q27E4SFEXQG2W:/var/lib/docker/overlay2/l/NQPXCTGZSYJ4OT3SGB7T4PVBZN:/var/lib/docker/overlay2/l/T4QOH4WZ5SCANXAUZG4KYAEJYA:/var/lib/docker/overlay2/l/MZLUXGBJ6TVWZZ5U4JR2DLQTF5:/v'
> Unexpected end of /proc/mounts line `ar/lib/docker/overlay2/l/UB4H4RWMEBU6MPAHUONLNWOXME:/var/lib/docker/overlay2/l/ZDFVRZHFUZQ2LMPIXYT3QMBR7S:/var/lib/docker/overlay2/l/WREGKWGU3ROBZVKFTI77FZSR2Y:/var/lib/docker/overlay2/l/MFY7FSVWFFABVARUG3HGOR7AS3:/var/lib/docker/overlay2/l/PYM25PD7YWSMHEAHOXX3F3BN2G:/var/lib/docker/overlay2/l/XBOHFR5TGPUIRBO4KRKBU4QVVE:/var/lib/docker/overlay2/l/CMEF2O3B3MESXN55HZ6WUWCQDN:/var/lib/docker/overlay2/l/G4STMCPL6MLUMIO3A36J4GLU2T:/var/lib/docker/overlay2/l/6I5ZFVHVR7HWJ2YB7UPLD6WDWA:/var/lib/docker/overlay2/l/'
> Unexpected end of /proc/mounts line `overlay / overlay rw,seclabel,relatime,lowerdir=/var/lib/docker/overlay2/l/6RBW4KCZ3OYGYQAJJMXZFYAAMR:/var/lib/docker/overlay2/l/V3MA4Z2HBJZ6B7EZ65OAP7P537:/var/lib/docker/overlay2/l/MN266PQEUTU5BNCMLEJNNVILTT:/var/lib/docker/overlay2/l/TMGCIJQBHQQCVLSUJ2RRVS4XDM:/var/lib/docker/overlay2/l/TKESEQSOI53CYKGKILMGJI3UY4:/var/lib/docker/overlay2/l/B6QZ4DGG42FNN4JTS4GITRJGDL:/var/lib/docker/overlay2/l/SFNS2U7WQ5RSH6SNLBWXNYJONO:/var/lib/docker/overlay2/l/CBRFQTL36KJL2QYWZGHYLCPMXZ:/var/lib/docker/overlay2/l/WX6N'
> Unexpected end of /proc/mounts line `ZP7XCQR3ZP4M6LPBFDO52B:/var/lib/docker/overlay2/l/5UI72CMT25UJQ5Y254WJ3RH76R:/var/lib/docker/overlay2/l/VDSVENFVBUDY375WMRBHJ37VRQ:/var/lib/docker/overlay2/l/EHO5G2B7VBVYCRAD7E2HW7SR6B:/var/lib/docker/overlay2/l/CBLEIXX5A73KHGFU2PZ32K6UFB:/var/lib/docker/overlay2/l/IF5IYD43TJVTTOMRLMCWBL4ECB:/var/lib/docker/overlay2/l/MH53AACICBGKYBAMLPRC5SQ4IO:/var/lib/docker/overlay2/l/GWQFHWUBZS5OUCRSH3K333O734:/var/lib/docker/overlay2/l/FVFDM5C6OI4IUZ7W75HLVNACZ5:/var/lib/docker/overlay2/l/HKVPZESKV5BES7ICQN7C2CJL74:/v'
> Unexpected end of /proc/mounts line `ar/lib/docker/overlay2/l/CB22O4MAW7YME66UF2DW4FNQKA:/var/lib/docker/overlay2/l/63EE36FRFXPLLQ5MSANT5LAA4K:/var/lib/docker/overlay2/l/UIKDHWRS45N3UYA3OZVPBV6KFM:/var/lib/docker/overlay2/l/7AR75S33YT3JQGCEJJJNLEL2S4:/var/lib/docker/overlay2/l/YTC53ZBHNF2OJGKZC4AXWFF5SQ:/var/lib/docker/overlay2/l/OCJ4JEG2F3U6O7UABYYIIO5FMJ:/var/lib/docker/overlay2/l/YCKHOSYJYQN3ORDLCPEE2HQVGD:/var/lib/docker/overlay2/l/HFSGUFFNSF3JIDLA7P22JRD7W2:/var/lib/docker/overlay2/l/6SD64VXYTE6FUDWVYV6ARMAWAC:/var/lib/docker/overlay2/l/'
> workstation131:89:116 [0] INFO comm 0x7f2838221b20 rank 1 nranks 2
> workstation131:89:116 [0] INFO NET : Using interface enp5s0:192.168.0.131<0>
> workstation131:89:116 [0] INFO NET : Using interface virbr0:192.168.122.1<0>
> workstation131:89:116 [0] INFO NET : Using interface br-ac28397ce282:172.16.0.1<0>
> workstation131:89:116 [0] INFO NET : Using interface veth7738baf:fe80::7045:e9ff:fe5d:e3c9%veth7738baf<0>
> workstation131:89:116 [0] INFO NET : Using interface veth0e92c47:fe80::c884:41ff:fea3:aae7%veth0e92c47<0>
> workstation131:89:116 [0] INFO NET : Using interface veth2a1182a:fe80::28cb:f9ff:fe9c:913a%veth2a1182a<0>
> workstation131:89:116 [0] INFO NET : Using interface veth04f2087:fe80::446b:cff:feb9:13be%veth04f2087<0>
> workstation131:89:116 [0] INFO NET : Using interface veth09b7699:fe80::496:c2ff:fed9:179a%veth09b7699<0>
> workstation131:89:116 [0] INFO NET : Using interface veth725a806:fe80::4493:ff:fec8:fda3%veth725a806<0>
> workstation131:89:116 [0] INFO NET/Socket : 9 interfaces found
> workstation132:85:112 [0] INFO comm 0x7fdb04207010 rank 0 nranks 2
> workstation132:85:112 [0] INFO Using 256 threads
> workstation132:85:112 [0] INFO Min Comp Cap 5
> workstation132:85:112 [0] INFO NCCL_SINGLE_RING_THRESHOLD=131072
> workstation132:85:112 [0] INFO Ring 00 :    0   1
> workstation132:85:112 [0] INFO Ring 01 :    0   1
> workstation132:85:112 [0] INFO Ring 02 :    0   1
> workstation132:85:112 [0] INFO Ring 03 :    0   1
> workstation131:89:116 [0] INFO 0 -> 1 via NET/Socket/0
> workstation132:85:112 [0] INFO 1 -> 0 via NET/Socket/0
> workstation132:85:112 [0] INFO 1 -> 0 via NET/Socket/1
> workstation131:89:116 [0] INFO 0 -> 1 via NET/Socket/1
> 
> workstation131:89:116 [0] include/socket.h:360 WARN Call to connect timeout : Connection refused
> workstation131:89:116 [0] INFO transport/net_socket.cu:118 -> 2
> workstation131:89:116 [0] INFO include/net.h:32 -> 2 [Net]
> workstation131:89:116 [0] INFO transport/net.cu:266 -> 2
> workstation131:89:116 [0] INFO init.cu:475 -> 2
> workstation131:89:116 [0] INFO init.cu:536 -> 2
>

**Comment by alsrgv** [comment]
@ziqifan16, can you try specifying `-x NCCL_SOCKET_IFNAME= enp5s0` in your `mpirun` command?

**Comment by ziqifan16** [comment]
@alsrgv It works. Thank you so much!

**Comment by jageshmaharjan** [comment]
Sorry for reopening this issue.
@ziqifan16 , I exactly have the same issue, what do you mean by "another passwordless authentication method". Usually, the master and client are passwordless from my docker image.
Can you tell me how did you get rid of that error.

**Comment by wu-yy** [comment]
I also meet this problem. I solved it with "-x NCCL_SOCKET_IFNAME= enp129s0f0"  as @alsrgv .  before that ,my error function is"-x NCCL_SOCKET_IFNAME= ^enp129s0f0".

**Comment by Jeffwan** [comment]
I use this way and make it work  -mca btl_tcp_if_include ${my_network_name}

**Comment by wu-yy** [comment]
@Jeffwan  year, the network interface,you can specify one. 

you can also specify a ip:port ,like
`mpirun --mca btl_tcp_if_include 192.168.1.0/24,10.10.0.0/16  ` which require the MPI version is above 1.5.
instead of 
`mpirun --mca btl_tcp_if_include eth1,eth2`
