### ISSUE TITLE
fatal error: cuda.h: No such file or directory when install horovod0.13.8 for pytorch0.4.0

### ISSUE THREAD

**Issue by charlieguo0307** [uber/horovod#383]
Hello, I want to install horovod 0.13.8 and I preinstalled pytorch 0.4.0 in my python environment. Pytorch is installed with CUDA and when I typed "torch.cuda.is_available()" the return is True. 

My command line when installing horovod is 
HOROVOD_NCCL_HOME=nccl_2.1.15-1+cuda9.1_x86_64
HOROVOD_CUDA_HOME=cuda-9.1 
HOROVOD_GPU_ALLREDUCE=NCCL 
pytorch_0.4.0_c9.1_hvd_nccl/bin/pip3 install -v --no-cache-dir horovod

The log message is:
...
generating /tmp/tmpr97vj4xk/_test_cuda.c
    setting the current directory to '/tmp/tmpr97vj4xk'
    running build_ext
    building '_test_cuda' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/pytorch_0.4.0_c9.1_hvd_nccl/include/python3.6m -c _test_cuda.c -o ./_test_cuda.o -std=c11 -fPIC -O2
    In file included from /pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                     from _test_cuda.c:493:
    /pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file or directory
     #include "cuda.h"
                      ^
    compilation terminated.
    INFO: Above error indicates that this PyTorch installation does not support CUDA.
    INFO: Unable to build PyTorch plugin, will skip it.

So what is the problem? How can I fix it? thanks.

**Comment by tgaddair** [comment]
Hey @charlieguo0307, looks like an environment issue.  Could you take a look at [this](https://github.com/locuslab/pytorch_fft/issues/21) thread and see if any of the suggestions there work for you (check PATH and LD_LIBRARY_PATH, create soft links to versioned directories, etc.)?

**Comment by charlieguo0307** [comment]
Thanks @tgaddair !
The problem has been solved when I added cuda/include in PATH and cuda/lib64 in LD_LIBRARY_PATH.
But the log is also strange if I don't create soft links for /usr/local/cuda:

building '_test_cuda' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/include/python3.6m -c _test_cuda.c -o ./_test_cuda.o -std=c11 -fPIC -O2
    In file included from /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                     from _test_cuda.c:493:
    /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file or directory
     #include "cuda.h"
                      ^
    compilation terminated.
    INFO: Above error indicates that this PyTorch installation does not support CUDA.
    INFO: Unable to build PyTorch plugin, will skip it.

    Traceback (most recent call last):
      File "/data/chuangchen/qspace/tmp/pip-install-yk7u7xpy/horovod/setup.py", line 599, in build_extensions
        build_torch_extension(self, options, abi_compile_flags)
      File "/data/chuangchen/qspace/tmp/pip-install-yk7u7xpy/horovod/setup.py", line 524, in build_torch_extension
        'Horovod build with GPU support was requested, but this PyTorch '
    distutils.errors.DistutilsPlatformError: Horovod build with GPU support was requested, but this PyTorch installation does not support CUDA.

    building 'horovod.common.mpi_lib' extension
    creating build/temp.linux-x86_64-3.6/horovod/common
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_CUDA=1 -DHAVE_NCCL=1 -DHOROVOD_GPU_ALLREDUCE='N' -I/data/chuangchen/qspace/cuda-9.1/include -I/data/chuangchen/guocy/nccl_2.1.15-1+cuda9.1_x86_64/include -I/data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/include/python3.6m -c horovod/common/common.cc -o build/temp.linux-x86_64-3.6/horovod/common/common.o -std=c++11 -fPIC -O2 -I/data/chuangchen/qspace/mvapich2/include -L/data/chuangchen/qspace/mvapich2/lib -lmpicxx -Wl,-rpath -Wl,/data/chuangchen/qspace/mvapich2/lib -Wl,--enable-new-dtags -lmpi -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_CUDA=1 -DHAVE_NCCL=1 -DHOROVOD_GPU_ALLREDUCE='N' -I/data/chuangchen/qspace/cuda-9.1/include -I/data/chuangchen/guocy/nccl_2.1.15-1+cuda9.1_x86_64/include -I/data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/include/python3.6m -c horovod/common/mpi_message.cc -o build/temp.linux-x86_64-3.6/horovod/common/mpi_message.o -std=c++11 -fPIC -O2 -I/data/chuangchen/qspace/mvapich2/include -L/data/chuangchen/qspace/mvapich2/lib -lmpicxx -Wl,-rpath -Wl,/data/chuangchen/qspace/mvapich2/lib -Wl,--enable-new-dtags -lmpi -D_GLIBCXX_USE_CXX11_ABI=0

Indeed, from the gcc command line, horovod with GPU is compiled and in the final line the horovod installation is successful. 

So is horovod is compiled with GPU in this situation?

**Comment by charlieguo0307** [comment]
@alsrgv Yes, the HOROVOD_CUDA_HOME environment variable is set but the problem still exists as the first comment says. So I am confused about it.

**Comment by alsrgv** [comment]
@charlieguo0307, could you paste the full installation log as a gist?

**Comment by charlieguo0307** [comment]
`  Running setup.py (path:/data/chuangchen/qspace/tmp/pip-install-ccsd_bh0/horovod/setup.py) egg_info for package horovod
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/horovod.egg-info
    writing pip-egg-info/horovod.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/horovod.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/horovod.egg-info/requires.txt
    writing top-level names to pip-egg-info/horovod.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/horovod.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/horovod.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching '.eggs'
    writing manifest file 'pip-egg-info/horovod.egg-info/SOURCES.txt'
  Source in ./tmp/pip-install-ccsd_bh0/horovod has version 0.13.10, which satisfies requirement horovod from http://mirror-sng.oa.com/pypi/web/packages/2c/7e/54f7759bc693ab19480c1b525decab5c1d846cd5fc3af97bda18364a1aa5/horovod-0.13.10.tar.gz#sha256=a28201d988a4165297ca85ee8f6b41c26c9d3f631e69918eebb1173cde7fbd5a
Requirement already satisfied: cffi>=1.4.0 in ./pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages (from horovod) (1.11.5)
Requirement already satisfied: pycparser in ./pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages (from cffi>=1.4.0->horovod) (2.18)
Installing collected packages: horovod
  Created temporary directory: /data/chuangchen/qspace/tmp/pip-record-uic33lvk
  Running setup.py install for horovod ...     Running command /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/data/chuangchen/qspace/tmp/pip-install-ccsd_bh0/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/chuangchen/qspace/tmp/pip-record-uic33lvk/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-3.6/horovod
    creating build/lib.linux-x86_64-3.6/horovod/torch
    copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/torch
    copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch
    creating build/lib.linux-x86_64-3.6/horovod/common
    copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.6/horovod/common
    creating build/lib.linux-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
    creating build/lib.linux-x86_64-3.6/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.6/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.6/horovod/keras
    creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
    copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
    creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
    copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
    running build_ext
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -shared build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.so
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/data/chuangchen/qspace/cuda-9.1/include -I/data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_cuda.cc -o build/temp.linux-x86_64-3.6/test_compile/test_cuda.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -shared build/temp.linux-x86_64-3.6/test_compile/test_cuda.o -L/data/chuangchen/qspace/cuda-9.1/lib -L/data/chuangchen/qspace/cuda-9.1/lib64 -lcudart -o build/temp.linux-x86_64-3.6/test_compile/test_cuda.so
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/data/chuangchen/guocy/nccl_2.1.15-1+cuda9.1_x86_64/include -I/data/chuangchen/qspace/cuda-9.1/include -I/data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_nccl.cc -o build/temp.linux-x86_64-3.6/test_compile/test_nccl.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -shared build/temp.linux-x86_64-3.6/test_compile/test_nccl.o -L/data/chuangchen/guocy/nccl_2.1.15-1+cuda9.1_x86_64/lib -L/data/chuangchen/guocy/nccl_2.1.15-1+cuda9.1_x86_64/lib64 -L/data/chuangchen/qspace/cuda-9.1/lib -L/data/chuangchen/qspace/cuda-9.1/lib64 -lnccl_static -o build/temp.linux-x86_64-3.6/test_compile/test_nccl.so
    building 'horovod.tensorflow.mpi_lib' extension
    creating build/temp.linux-x86_64-3.6/horovod
    creating build/temp.linux-x86_64-3.6/horovod/tensorflow
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_CUDA=1 -DHAVE_NCCL=1 -DHOROVOD_GPU_ALLREDUCE='N' -I/data/chuangchen/qspace/cuda-9.1/include -I/data/chuangchen/guocy/nccl_2.1.15-1+cuda9.1_x86_64/include -I/data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/include/python3.6m -c horovod/tensorflow/mpi_ops.cc -o build/temp.linux-x86_64-3.6/horovod/tensorflow/mpi_ops.o -std=c++11 -fPIC -O2 -I/data/chuangchen/qspace/mvapich2/include -L/data/chuangchen/qspace/mvapich2/lib -lmpicxx -Wl,-rpath -Wl,/data/chuangchen/qspace/mvapich2/lib -Wl,--enable-new-dtags -lmpi -I/data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    g++ -pthread -shared build/temp.linux-x86_64-3.6/horovod/tensorflow/mpi_ops.o -L/data/chuangchen/qspace/cuda-9.1/lib -L/data/chuangchen/qspace/cuda-9.1/lib64 -L/data/chuangchen/guocy/nccl_2.1.15-1+cuda9.1_x86_64/lib -L/data/chuangchen/guocy/nccl_2.1.15-1+cuda9.1_x86_64/lib64 -lcudart -lnccl_static -o build/lib.linux-x86_64-3.6/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so -I/data/chuangchen/qspace/mvapich2/include -L/data/chuangchen/qspace/mvapich2/lib -lmpicxx -Wl,-rpath -Wl,/data/chuangchen/qspace/mvapich2/lib -Wl,--enable-new-dtags -lmpi -Wl,--version-script=hide_nccl.lds -L/data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/tensorflow -ltensorflow_framework
    generating /data/chuangchen/qspace/tmp/tmpkw55uvm9/_test_cuda.c
    setting the current directory to '/data/chuangchen/qspace/tmp/tmpkw55uvm9'
    running build_ext
    building '_test_cuda' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/include/python3.6m -c _test_cuda.c -o ./_test_cuda.o -std=c11 -fPIC -O2
    In file included from /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                     from _test_cuda.c:493:
    /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file or directory
     #include "cuda.h"
                      ^
    compilation terminated.
    INFO: Above error indicates that this PyTorch installation does not support CUDA.
    INFO: Unable to build PyTorch plugin, will skip it.

    Traceback (most recent call last):
      File "/data/chuangchen/qspace/tmp/pip-install-ccsd_bh0/horovod/setup.py", line 599, in build_extensions
        build_torch_extension(self, options, abi_compile_flags)
      File "/data/chuangchen/qspace/tmp/pip-install-ccsd_bh0/horovod/setup.py", line 524, in build_torch_extension
        'Horovod build with GPU support was requested, but this PyTorch '
    distutils.errors.DistutilsPlatformError: Horovod build with GPU support was requested, but this PyTorch installation does not support CUDA.

    building 'horovod.common.mpi_lib' extension
    creating build/temp.linux-x86_64-3.6/horovod/common
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_CUDA=1 -DHAVE_NCCL=1 -DHOROVOD_GPU_ALLREDUCE='N' -I/data/chuangchen/qspace/cuda-9.1/include -I/data/chuangchen/guocy/nccl_2.1.15-1+cuda9.1_x86_64/include -I/data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/include/python3.6m -c horovod/common/common.cc -o build/temp.linux-x86_64-3.6/horovod/common/common.o -std=c++11 -fPIC -O2 -I/data/chuangchen/qspace/mvapich2/include -L/data/chuangchen/qspace/mvapich2/lib -lmpicxx -Wl,-rpath -Wl,/data/chuangchen/qspace/mvapich2/lib -Wl,--enable-new-dtags -lmpi -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_CUDA=1 -DHAVE_NCCL=1 -DHOROVOD_GPU_ALLREDUCE='N' -I/data/chuangchen/qspace/cuda-9.1/include -I/data/chuangchen/guocy/nccl_2.1.15-1+cuda9.1_x86_64/include -I/data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/include/python3.6m -c horovod/common/mpi_message.cc -o build/temp.linux-x86_64-3.6/horovod/common/mpi_message.o -std=c++11 -fPIC -O2 -I/data/chuangchen/qspace/mvapich2/include -L/data/chuangchen/qspace/mvapich2/lib -lmpicxx -Wl,-rpath -Wl,/data/chuangchen/qspace/mvapich2/lib -Wl,--enable-new-dtags -lmpi -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_CUDA=1 -DHAVE_NCCL=1 -DHOROVOD_GPU_ALLREDUCE='N' -I/data/chuangchen/qspace/cuda-9.1/include -I/data/chuangchen/guocy/nccl_2.1.15-1+cuda9.1_x86_64/include -I/data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/include/python3.6m -c horovod/common/operations.cc -o build/temp.linux-x86_64-3.6/horovod/common/operations.o -std=c++11 -fPIC -O2 -I/data/chuangchen/qspace/mvapich2/include -L/data/chuangchen/qspace/mvapich2/lib -lmpicxx -Wl,-rpath -Wl,/data/chuangchen/qspace/mvapich2/lib -Wl,--enable-new-dtags -lmpi -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_CUDA=1 -DHAVE_NCCL=1 -DHOROVOD_GPU_ALLREDUCE='N' -I/data/chuangchen/qspace/cuda-9.1/include -I/data/chuangchen/guocy/nccl_2.1.15-1+cuda9.1_x86_64/include -I/data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/include/python3.6m -c horovod/common/timeline.cc -o build/temp.linux-x86_64-3.6/horovod/common/timeline.o -std=c++11 -fPIC -O2 -I/data/chuangchen/qspace/mvapich2/include -L/data/chuangchen/qspace/mvapich2/lib -lmpicxx -Wl,-rpath -Wl,/data/chuangchen/qspace/mvapich2/lib -Wl,--enable-new-dtags -lmpi -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    g++ -pthread -shared build/temp.linux-x86_64-3.6/horovod/common/common.o build/temp.linux-x86_64-3.6/horovod/common/mpi_message.o build/temp.linux-x86_64-3.6/horovod/common/operations.o build/temp.linux-x86_64-3.6/horovod/common/timeline.o -L/data/chuangchen/qspace/cuda-9.1/lib -L/data/chuangchen/qspace/cuda-9.1/lib64 -L/data/chuangchen/guocy/nccl_2.1.15-1+cuda9.1_x86_64/lib -L/data/chuangchen/guocy/nccl_2.1.15-1+cuda9.1_x86_64/lib64 -lcudart -lnccl_static -o build/lib.linux-x86_64-3.6/horovod/common/mpi_lib.cpython-36m-x86_64-linux-gnu.so -I/data/chuangchen/qspace/mvapich2/include -L/data/chuangchen/qspace/mvapich2/lib -lmpicxx -Wl,-rpath -Wl,/data/chuangchen/qspace/mvapich2/lib -Wl,--enable-new-dtags -lmpi -Wl,--version-script=hide_nccl.lds
    running install_lib
    creating /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod
    creating /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/torch
    creating /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/torch/mpi_lib_impl
    copying build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl/__init__.py -> /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/torch/mpi_lib_impl
    copying build/lib.linux-x86_64-3.6/horovod/torch/mpi_ops.py -> /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/torch
    copying build/lib.linux-x86_64-3.6/horovod/torch/__init__.py -> /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/torch
    creating /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/torch/mpi_lib
    copying build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib/__init__.py -> /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/torch/mpi_lib
    creating /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/common
    copying build/lib.linux-x86_64-3.6/horovod/common/mpi_lib.cpython-36m-x86_64-linux-gnu.so -> /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/common
    copying build/lib.linux-x86_64-3.6/horovod/common/__init__.py -> /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/common
    creating /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/tensorflow
    copying build/lib.linux-x86_64-3.6/horovod/tensorflow/mpi_ops.py -> /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/tensorflow
    copying build/lib.linux-x86_64-3.6/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so -> /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/tensorflow
    copying build/lib.linux-x86_64-3.6/horovod/tensorflow/__init__.py -> /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/tensorflow
    creating /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/keras
    copying build/lib.linux-x86_64-3.6/horovod/keras/callbacks.py -> /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/keras
    copying build/lib.linux-x86_64-3.6/horovod/keras/__init__.py -> /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/keras
    copying build/lib.linux-x86_64-3.6/horovod/__init__.py -> /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod
    byte-compiling /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/torch/mpi_lib_impl/__init__.py to __init__.cpython-36.pyc
    byte-compiling /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/torch/mpi_ops.py to mpi_ops.cpython-36.pyc
    byte-compiling /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/torch/__init__.py to __init__.cpython-36.pyc
    byte-compiling /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/torch/mpi_lib/__init__.py to __init__.cpython-36.pyc
    byte-compiling /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/common/__init__.py to __init__.cpython-36.pyc
    byte-compiling /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py to mpi_ops.cpython-36.pyc
    byte-compiling /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/tensorflow/__init__.py to __init__.cpython-36.pyc
    byte-compiling /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/keras/callbacks.py to callbacks.cpython-36.pyc
    byte-compiling /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/keras/__init__.py to __init__.cpython-36.pyc
    byte-compiling /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod/__init__.py to __init__.cpython-36.pyc
    running install_egg_info
    running egg_info
    writing horovod.egg-info/PKG-INFO
    writing dependency_links to horovod.egg-info/dependency_links.txt
    writing requirements to horovod.egg-info/requires.txt
    writing top-level names to horovod.egg-info/top_level.txt
    reading manifest file 'horovod.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching '.eggs'
    writing manifest file 'horovod.egg-info/SOURCES.txt'
    Copying horovod.egg-info to /data/chuangchen/qspace/pytorch_0.4.0_c9.1_hvd_nccl/lib/python3.6/site-packages/horovod-0.13.10-py3.6.egg-info
    running install_scripts
    writing list of installed files to '/data/chuangchen/qspace/tmp/pip-record-uic33lvk/install-record.txt'
done
  Removing source in /data/chuangchen/qspace/tmp/pip-install-ccsd_bh0/horovod
Successfully installed horovod-0.13.10
Cleaning up...
`

**Comment by charlieguo0307** [comment]
@alsrgv the script is 
export HOROVOD_CUDA_HOME=/data/chuangchen/qspace/cuda-9.1
export PATH=${HOROVOD_CUDA_HOME}/include:$PATH
export LD_LIBRARY_PATH=${HOROVOD_CUDA_HOME}/lib64:$LD_LIBRARY_PATH

HOROVOD_NCCL_HOME=/data/chuangchen/guocy/nccl_2.1.15-1+cuda9.1_x86_64 HOROVOD_CUDA_HOME=/data/chuangchen/qspace/cuda-9.1 HOROVOD_GPU_ALLREDUCE=NCCL pytorch_0.4.0_c9.1_hvd_nccl/bin/pip3 install -v --no-cache-dir horovod

**Comment by alsrgv** [comment]
@charlieguo0307, looks like PyTorch is rather prescriptive about CUDA location at this point:
```
            cuda_include_dirs = glob.glob('/usr/local/cuda/include')
            cuda_include_dirs += glob.glob('/Developer/NVIDIA/CUDA-*/include')
```

Is it an option for you to make a symlink /usr/local/cuda -> /data/chuangchen/qspace/cuda-9.1?

**Comment by charlieguo0307** [comment]
@alsrgv Thanks a lot! My problem has been solved when creating a soft link to my local CUDA dir.

**Comment by relh** [comment]
For me, I don't have root access. I can't make such symlinks to the system. So I just symlinked to the problem dir and it works now. Not recommending this, just for those in a similar situation to me with whom no environmental variable setting has helped.

ln -s ~/cuda/include/* ~/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/
