### ISSUE TITLE
unable to run tensorflow_mnist example on muti nodes

### ISSUE THREAD

**Issue by tingweiwu** [uber/horovod#450]
I hava run two container on two nodes with host network.  
and mount the host dir "/root/.ssh" to container dir /mnt/share/ssh
and two nodes are passwordless authentication.

I use the images uber/horovod:0.13.10-tf1.9.0-torch0.4.0-py3.5
https://hub.docker.com/r/uber/horovod/

```
on first node
root@gpu8c-0003:/examples#   mpirun -np 2 -H 192.168.70.27:1,192.168.70.117:1 -bind-to none -map-by slot -x NCCL_SOCKET_IFNAME=eth0 -mca btl_tcp_if_include eth0 -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -mca plm_rsh_args "-p 12345 -vvvv" python tensorflow_mnist.py

on second node
root@ecs-gpu-2:/examples# bash -c "/usr/sbin/sshd -p 12345; sleep infinity"
```

and i get error in first node logs as follow
```
OpenSSH_7.2p2 Ubuntu-4ubuntu2.4, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "192.168.70.117" port 12345
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 192.168.70.117 [192.168.70.117] port 12345.
debug1: Connection established.
debug1: permanently_set_uid: 0/0
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.4 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 192.168.70.117:12345 as 'root'
debug3: put_host_port: [192.168.70.117]:12345
debug3: hostkeys_foreach: reading file "/root/.ssh/known_hosts"
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:TJgnyd4IanF1ORqZjjpLAKgfdCAEwsVcAZWTKvNKLhw
debug3: put_host_port: [192.168.70.117]:12345
debug3: put_host_port: [192.168.70.117]:12345
debug3: hostkeys_foreach: reading file "/root/.ssh/known_hosts"
debug3: hostkeys_foreach: reading file "/root/.ssh/known_hosts"
debug1: checking without port identifier
debug3: hostkeys_foreach: reading file "/root/.ssh/known_hosts"
Warning: Permanently added '[192.168.70.117]:12345' (ECDSA) to the list of known hosts.
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug2: set_newkeys: mode 0
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS received
debug2: key: /root/.ssh/id_rsa ((nil))
debug2: key: /root/.ssh/id_dsa ((nil))
debug2: key: /root/.ssh/id_ecdsa ((nil))
debug2: key: /root/.ssh/id_ed25519 ((nil))
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /root/.ssh/id_rsa
debug3: no such identity: /root/.ssh/id_rsa: No such file or directory
debug1: Trying private key: /root/.ssh/id_dsa
debug3: no such identity: /root/.ssh/id_dsa: No such file or directory
debug1: Trying private key: /root/.ssh/id_ecdsa
debug3: no such identity: /root/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /root/.ssh/id_ed25519
debug3: no such identity: /root/.ssh/id_ed25519: No such file or directory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup password
debug3: remaining preferred: ,password
debug3: authmethod_is_enabled password
debug1: Next authentication method: password


```

**Comment by alsrgv** [comment]
@tingweiwu, instead of mouting host `/root/.ssh` into container `/mnt/share/ssh`, you should mount directory with ssh keys into **container** `/root/.ssh`.  If you set up passwordless auth keys in `/root/.ssh`, you can mount `/root/.ssh` -> `/root/.ssh`.

**Comment by tingweiwu** [comment]
on first container 
![image](https://user-images.githubusercontent.com/29671725/44253329-d37bc000-a231-11e8-9632-65f5aba759ca.png)

on sencond container 

![image](https://user-images.githubusercontent.com/29671725/44253343-e1314580-a231-11e8-8bd6-d5548be42334.png)

**Comment by tingweiwu** [comment]
@alsrgv  ok, I will try as you said

**Comment by tingweiwu** [comment]
@alsrgv , I have tried mount /root/.ssh -> /root/.ssh  and continue to run the tensorflow_mnist example. this times, I get error as follows. 
It seems that still have communicate problems
I wonder whether I set  "btl_tcp_if_include eth0" impact or not?

```shell
debug1: Sending command:     PATH=/usr/local/bin:$PATH ; export PATH ; LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH ; export LD_LIBRARY_PATH ; DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH ; export DYLD_LIBRARY_PATH ;   /usr/local/bin/orted -mca ess "env" -mca ess_base_jobid "1160183808" -mca ess_base_vpid 1 -mca ess_base_num_procs "2" -mca orte_node_regex "gpu8c-0003,192.168.70.117@0(2)" -mca orte_hnp_uri "1160183808.0;tcp://192.168.70.27,172.17.0.1,172.16.203.128:52605" -mca btl_tcp_if_include "eth0" -mca plm "rsh" -mca plm_rsh_args "-p 12345 -vvvv" -mca hwloc_base_binding_policy "none" -mca rmaps_base_mapping_policy "slot" -mca pmix "^s1,s2,cray,isolated"
debug2: channel 0: request exec confirm 1
debug3: send packet: type 98
debug2: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
debug2: channel 0: read<=0 rfd 4 len 0
debug2: channel 0: read failed
debug2: channel 0: close_read
debug2: channel 0: input open -> drain
debug2: channel 0: ibuf empty
debug2: channel 0: send eof
debug3: send packet: type 96
debug2: channel 0: input drain -> closed
--------------------------------------------------------------------------
Two mutually-exclusive MCA variables were specified.  This can result
in undefined behavior, such as ignoring the components that the MCA
variables are supposed to affect.

  1st MCA variable: btl_tcp_if_include
    Source of value: environment
  2nd MCA variable: btl_tcp_if_exclude
    Source of value: file (/usr/local/etc/openmpi-mca-params.conf:61)
--------------------------------------------------------------------------
--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[17703,1],1]) is on host: ecs-gpu-2
  Process 2 ([[17703,1],0]) is on host: gpu8c-0003
  BTLs attempted: self

Your MPI job is now going to abort; sorry.

```

**Comment by alsrgv** [comment]
@tingweiwu, yes, can you try removing `-mca btl_tcp_if_include eth0` ?

**Comment by tingweiwu** [comment]
@alsrgv remove `-mca btl_tcp_if_include eth0` get error as follows and hang at this point

```
debug1: Sending command:     PATH=/usr/local/bin:$PATH ; export PATH ; LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH ; export LD_LIBRARY_PATH ; DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH ; export DYLD_LIBRARY_PATH ;   /usr/local/bin/orted -mca ess "env" -mca ess_base_jobid "1161428992" -mca ess_base_vpid 1 -mca ess_base_num_procs "2" -mca orte_node_regex "gpu8c-0003,192.168.70.117@0(2)" -mca orte_hnp_uri "1161428992.0;tcp://192.168.70.27,172.17.0.1,172.16.203.128:45413" -mca plm "rsh" -mca plm_rsh_args "-p 12345 -vvvv" -mca hwloc_base_binding_policy "none" -mca rmaps_base_mapping_policy "slot" -mca pmix "^s1,s2,cray,isolated"
debug2: channel 0: request exec confirm 1
debug3: send packet: type 98
debug2: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
debug2: channel 0: read<=0 rfd 4 len 0
debug2: channel 0: read failed
debug2: channel 0: close_read
debug2: channel 0: input open -> drain
debug2: channel 0: ibuf empty
debug2: channel 0: send eof
debug3: send packet: type 96
debug2: channel 0: input drain -> closed
[ecs-gpu-2][[17722,1],1][btl_tcp_endpoint.c:796:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.203.128 failed: Connection timed out (110)
...
```

and I  add `-mca btl_tcp_if_exclude docker0,tunl0,lo ` the whole command as follows  and solved this problem
```
mpirun -np 2 -H 192.168.70.27:1,192.168.70.117:1 -bind-to none -map-by slot -x NCCL_SOCKET_IFNAME=eth0 -mca btl_tcp_if_exclude docker0,tunl0,lo -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -mca plm_rsh_args "-p 12345 -vvvv" python tensorflow_mnist.py

```

and the following is my first node `ifconfig` output.
 I confused that whether I should exclude all except eth0? because I have some unconfirmed network like `cali3ec275e4919` which is generated when a new k8s pod is running on this node.

```
[root@gpu8c-0003 ~]# ifconfig
cali3ec275e4919: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::ecee:eeff:feee:eeee  prefixlen 64  scopeid 0x20<link>
        ether ee:ee:ee:ee:ee:ee  txqueuelen 0  (Ethernet)
        RX packets 27  bytes 1896 (1.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 11  bytes 774 (774.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::42:ccff:fe84:7ebd  prefixlen 64  scopeid 0x20<link>
        ether 02:42:cc:84:7e:bd  txqueuelen 0  (Ethernet)
        RX packets 27  bytes 1896 (1.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 11  bytes 774 (774.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.70.27  netmask 255.255.255.0  broadcast 192.168.70.255
        inet6 fe80::f816:3eff:feb8:e664  prefixlen 64  scopeid 0x20<link>
        ether fa:16:3e:b8:e6:64  txqueuelen 1000  (Ethernet)
        RX packets 6347970  bytes 5670523616 (5.2 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3831084  bytes 11123935777 (10.3 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 1887823  bytes 133246172 (127.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1887823  bytes 133246172 (127.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tunl0: flags=193<UP,RUNNING,NOARP>  mtu 1440
        inet 172.16.203.128  netmask 255.255.255.255
        tunnel   txqueuelen 0  (IPIP Tunnel)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 226  bytes 21384 (20.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth8c64ad6: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::e8a7:c5ff:fea5:df82  prefixlen 64  scopeid 0x20<link>
        ether ea:a7:c5:a5:df:82  txqueuelen 0  (Ethernet)
        RX packets 27  bytes 2274 (2.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 19  bytes 1422 (1.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```

**Comment by alsrgv** [comment]
@tingweiwu, makes sense - glad you were able to resolve the issue!

**Comment by tingweiwu** [comment]
@alsrgv but I can not list all the network card to exclude because part of them is dynamically generated. Is there a good suggestion to solve this?

**Comment by alsrgv** [comment]
@tingweiwu, sure - you can replace `btl_tcp_if_exclude = lo,docker0` with `btl_tcp_if_include = eth0` in `/usr/local/etc/openmpi-mca-params.conf` inside the docker.

**Comment by tingweiwu** [comment]
@alsrgv I will try this proposal. Thanks a lot
