### ISSUE TITLE
Horovod MPI job is expected to abort when horovod has been shutdown

### ISSUE THREAD

**Issue by LiweiPeng** [uber/horovod#552]
I have been used horovod (0.14.x, 0.15.0) to run tensorflow jobs. Sometimes my job used too much GPU memory and it hit OOM error. At this point, horovod reported error like below. MPI+horovod continued running with constant errors until I manually killed all the processes.

What I expect is that the mpi+horovod process will abort so that all the GPU resources can be freed. But this never happened.

The horovod error is like below

E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 512.00M (536870912 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
...

AbortedError (see above for traceback): Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
	 [[{{node HorovodBroadcast_NmtModel_decoder_layer_1_layer_norm_1_layer_norm_bias_0}} = HorovodBroadcast[T=DT_FLOAT, root_rank=0, _device="/job:localhost/replica:0/task:0/device:GPU:0"](NmtModel/decoder/layer_1/layer_norm_1/layer_norm_bias/read)]]
...
tensorflow was continuing running and continue has errors.

**Comment by LiweiPeng** [comment]
One simple repro for this issue is: use MPI with 2 processes to run a tf+hvd job. One process uses normal batch size. Another process uses a batch size that'll cause OOM. When this occurs, the horovod+tf job goes to endless error state.

The expected behavior when horovod found this error is to call MPI_Abort(). So that all the MPI processes can be properly cleaned up.

**Comment by alsrgv** [comment]
@LiweiPeng, I have followed your repro with `tensorflow_mnist_estimator.py` example.  I am able to see AbortedError, however, it seems that in case of an Estimator, TensorFlow treats those errors as retryable:

```
Wed Oct 10 23:42:03 2018[1,3]<stderr>:INFO:tensorflow:An error was raised while a session was being created. This may be due to a preemption of a connected worker or parameter server. A new session will be created. Error: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
```

Are you using an Estimator in your scenario?

**Comment by LiweiPeng** [comment]
@alsrgv I am using Estimator. Thanks for handling this issue quickly.

**Comment by LiweiPeng** [comment]
I verified the fix in latest horovod code. My issue was resolved successfully! Thanks!
