### ISSUE TITLE
Horovod hangs on multi-machine

### ISSUE THREAD

**Issue by qyyy** [uber/horovod#584]
I run the [tensorflow benchmark example](https://github.com/tensorflow/benchmarks/tree/cnn_tf_v1.10_compatible) in the [official docker image](https://hub.docker.com/r/uber/horovod/tags/)(uber/horovod:0.14.1-tf1.10.0-torch0.4.0-py2.7). And I run the example in docker.
When I just run the example on single mechine(docker1 on server "main-0"):`mpirun -np 2 -H main-0:2 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH  -mca pml ob1 -mca btl ^openib  python benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --model resnet20 --batch_size 32 --data_dir=cifar-10-batches-py  --data_name=cifar10 --train_dir=output --variable_update horovod`, it runs correctly. Even if I submit the mpi job on another server("worker-0")`mpirun -np 2 -H worker-0:2 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH  -mca pml ob1 -mca btl ^openib  python benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --model resnet20 --batch_size 32 --data_dir=cifar-10-batches-py  --data_name=cifar10 --train_dir=output --variable_update horovod` from "main-0", it also works correctly.
But when I run it on two servers: `mpirun -np 4 -H worker-0:2,main-0:2 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x NCCL_SOCKET_IFNAME=^docker0 -x NCCL_IB_DISABLE=1 -mca pml ob1 -mca btl ^openib -mca btl_tcp_if_exclude docker0,lo  python benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --model resnet20 --batch_size 32 --data_dir=cifar-10-batches-py  --data_name=cifar10 --train_dir=output --variable_update horovod`, it hangs. And the message is following:
```
Warning: Permanently added '[10.151.40.239]:22917' (ECDSA) to the list of known hosts.
Warning: Permanently added '[10.151.40.240]:27523' (ECDSA) to the list of known hosts.
TensorFlow:  1.10
Model:       resnet20
Dataset:     cifar10
Mode:        training
SingleSess:  False
Batch size:  128 global
             32 per device
Num batches: 100
Num epochs:  0.26
Devices:     ['horovod/gpu:0', 'horovod/gpu:1', 'horovod/gpu:2', 'horovod/gpu:3']
Data format: NCHW
Optimizer:   sgd
Variables:   horovod
==========
TensorFlow:  1.10
Model:       resnet20
Dataset:     cifar10
Mode:        training
SingleSess:  False
Batch size:  128 global
             32 per device
Num batches: 100
Num epochs:  0.26
Devices:     ['horovod/gpu:0', 'horovod/gpu:1', 'horovod/gpu:2', 'horovod/gpu:3']
Data format: NCHW
Optimizer:   sgd
Variables:   horovod
==========
TensorFlow:  1.10
Model:       resnet20
Dataset:     cifar10
Mode:        training
SingleSess:  False
Batch size:  128 global
             32 per device
Num batches: 100
Num epochs:  0.26
Devices:     ['horovod/gpu:0', 'horovod/gpu:1', 'horovod/gpu:2', 'horovod/gpu:3']
Data format: NCHW
Optimizer:   sgd
Variables:   horovod
==========
TensorFlow:  1.10
Model:       resnet20
Dataset:     cifar10
Mode:        training
SingleSess:  False
Batch size:  128 global
             32 per device
Num batches: 100
Num epochs:  0.26
Devices:     ['horovod/gpu:0', 'horovod/gpu:1', 'horovod/gpu:2', 'horovod/gpu:3']
Data format: NCHW
Optimizer:   sgd
Variables:   horovod
==========
Generating model
Generating model
Generating model
Generating model
W1024 08:08:24.285554 139699888641792 tf_logging.py:125] From /root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py:1845: __init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
W1024 08:08:24.301079 140037811304192 tf_logging.py:125] From /root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py:1845: __init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
W1024 08:07:34.120145 139965457123072 tf_logging.py:125] From /root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py:1845: __init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
W1024 08:07:34.348869 140503711635200 tf_logging.py:125] From /root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py:1845: __init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
2018-10-24 08:08:25.527885: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-24 08:08:25.571825: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-24 08:07:35.371463: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-24 08:07:35.606027: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: e340:00:00.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-10-24 08:07:35.606079: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 1
2018-10-24 08:07:35.617946: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-24 08:08:25.903224: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: d132:00:00.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-10-24 08:08:25.903282: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2018-10-24 08:08:25.907247: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: e945:00:00.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-10-24 08:08:25.907299: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 1
2018-10-24 08:07:35.772379: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0cdf:00:00.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-10-24 08:07:35.772440: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2018-10-24 08:07:35.997089: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-10-24 08:07:35.997163: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      1
2018-10-24 08:07:35.997174: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 1:   N
2018-10-24 08:07:35.997472: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10750 MB memory) -> physical GPU (device: 1, name: Tesla K80, pci bus id: e340:00:00.0, compute capability: 3.7)
2018-10-24 08:08:26.240564: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-10-24 08:08:26.240639: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0
2018-10-24 08:08:26.240652: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N
2018-10-24 08:08:26.240951: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10750 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: d132:00:00.0, compute capability: 3.7)
2018-10-24 08:08:26.250096: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-10-24 08:08:26.250161: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      1
2018-10-24 08:08:26.250173: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 1:   N
2018-10-24 08:08:26.250594: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10750 MB memory) -> physical GPU (device: 1, name: Tesla K80, pci bus id: e945:00:00.0, compute capability: 3.7)
2018-10-24 08:07:36.117013: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-10-24 08:07:36.117084: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0
2018-10-24 08:07:36.117096: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N
2018-10-24 08:07:36.117405: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10750 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0cdf:00:00.0, compute capability: 3.7)
I1024 08:07:36.301609 139965457123072 tf_logging.py:115] Running local_init_op.
I1024 08:07:36.323522 139965457123072 tf_logging.py:115] Done running local_init_op.
I1024 08:08:26.580421 139699888641792 tf_logging.py:115] Running local_init_op.
I1024 08:08:26.586585 140037811304192 tf_logging.py:115] Running local_init_op.
I1024 08:08:26.605680 139699888641792 tf_logging.py:115] Done running local_init_op.
I1024 08:08:26.613028 140037811304192 tf_logging.py:115] Done running local_init_op.
I1024 08:07:36.411135 139965457123072 tf_logging.py:115] Starting standard services.
W1024 08:07:36.411349 139965457123072 tf_logging.py:125] Standard services need a 'logdir' passed to the SessionManager
I1024 08:07:36.411427 139965457123072 tf_logging.py:115] Starting queue runners.
I1024 08:07:36.430958 140503711635200 tf_logging.py:115] Running local_init_op.
I1024 08:07:36.454883 140503711635200 tf_logging.py:115] Done running local_init_op.
I1024 08:08:26.698084 139699888641792 tf_logging.py:115] Starting standard services.
W1024 08:08:26.698316 139699888641792 tf_logging.py:125] Standard services need a 'logdir' passed to the SessionManager
I1024 08:08:26.698396 139699888641792 tf_logging.py:115] Starting queue runners.
I1024 08:08:26.701816 140037811304192 tf_logging.py:115] Starting standard services.
W1024 08:08:26.702043 140037811304192 tf_logging.py:125] Standard services need a 'logdir' passed to the SessionManager
I1024 08:08:26.702122 140037811304192 tf_logging.py:115] Starting queue runners.
[paigcr-b-gpu-1011:04289] Read -1, expected 8577, errno = 1
I1024 08:08:38.643414 140503711635200 tf_logging.py:115] Starting standard services.
I1024 08:08:38.644509 140503711635200 tf_logging.py:115] Starting queue runners.
Running warm up
Running warm up
Running warm up
Running warm up
paigcr-b-gpu-1011:4289:4343 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
paigcr-b-gpu-1011:4289:4343 [0] NCCL INFO Using internal Network Socket
paigcr-b-gpu-1011:4289:4343 [0] NCCL INFO NET : Using interface lo:127.0.0.1<0>
paigcr-b-gpu-1011:4289:4343 [0] NCCL INFO NET : Using interface eth0:10.151.40.239<0>
paigcr-b-gpu-1011:4289:4343 [0] NCCL INFO NET : Using interface eth1:fe80::215:5dff:fe33:ff6c%eth1<0>
paigcr-b-gpu-1011:4289:4343 [0] NCCL INFO NET/Socket : 3 interfaces found
NCCL version 2.3.5+cuda9.0
paigcr-b-gpu-1011:4289:4343 [0] NCCL INFO rank 0 nranks 4
paigcr-b-gpu-1011:4290:4344 [1] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
paigcr-b-gpu-1011:4290:4344 [1] NCCL INFO Using internal Network Socket
paigcr-b-gpu-1011:4290:4344 [1] NCCL INFO rank 1 nranks 4
paigcr-b-gpu-1012:4153:4209 [1] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
paigcr-b-gpu-1012:4153:4209 [1] NCCL INFO Using internal Network Socket
paigcr-b-gpu-1012:4153:4209 [1] NCCL INFO rank 3 nranks 4
paigcr-b-gpu-1012:4152:4206 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
paigcr-b-gpu-1012:4152:4206 [0] NCCL INFO Using internal Network Socket
paigcr-b-gpu-1012:4152:4206 [0] NCCL INFO rank 2 nranks 4
Unexpected end of /proc/mounts line `overlay / overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/IIP2H67OCJBIGPXFIITBMU6RAQ:/var/lib/docker/overlay2/l/5GMU5RDNATNPWANBS5PS7XVXLO:/var/lib/docker/overlay2/l/YIISGY5TCRJPU7NUNOB2QFCKIM:/var/lib/docker/overlay2/l/IAYK2Z6HM5B6XI2GT55MIOSSLI:/var/lib/docker/overlay2/l/7GJGZBWLHDQEVO7RETWSRRELUB:/var/lib/docker/overlay2/l/U2A3ZE5UJ2CPBZHLYYJYXJWWWQ:/var/lib/docker/overlay2/l/G5PIVH4STEPIUDMZXB4XB34EIZ:/var/lib/docker/overlay2/l/VGR5NCRKGZBBRQPW2Q3722OKCY:/var/lib/docker/overlay2/l/26PYXC4PMMDU6'
Unexpected end of /proc/mounts line `TFQ3KGDIZ44FE:/var/lib/docker/overlay2/l/XGESBQ3AZIEWQUJ3GLTNNTGYUT:/var/lib/docker/overlay2/l/ERANPYRKYNV3DEG2ZGQ3AXWACU:/var/lib/docker/overlay2/l/P6BAVZTG34GSBSZILGZUXRGYH6:/var/lib/docker/overlay2/l/YIV34GB2LRZ2X5JC6CKMQLYHAV:/var/lib/docker/overlay2/l/N2MS6NFUCEGMZUIXD2XEJ7C6U5:/var/lib/docker/overlay2/l/VO7OOGE4H6IZE7NAQXMWDOHINZ:/var/lib/docker/overlay2/l/LSMIOCVFL5QZ63IXID2ENZYNEH:/var/lib/docker/overlay2/l/CEHVBB7QBAD3EKUNNGUSM6Q24M:/var/lib/docker/overlay2/l/6VYZTVC4FNKJDA5YQTEXL4CCPP:/var/lib/do'
Unexpected end of /proc/mounts line `overlay / overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/IIP2H67OCJBIGPXFIITBMU6RAQ:/var/lib/docker/overlay2/l/5GMU5RDNATNPWANBS5PS7XVXLO:/var/lib/docker/overlay2/l/YIISGY5TCRJPU7NUNOB2QFCKIM:/var/lib/docker/overlay2/l/IAYK2Z6HM5B6XI2GT55MIOSSLI:/var/lib/docker/overlay2/l/7GJGZBWLHDQEVO7RETWSRRELUB:/var/lib/docker/overlay2/l/U2A3ZE5UJ2CPBZHLYYJYXJWWWQ:/var/lib/docker/overlay2/l/G5PIVH4STEPIUDMZXB4XB34EIZ:/var/lib/docker/overlay2/l/VGR5NCRKGZBBRQPW2Q3722OKCY:/var/lib/docker/overlay2/l/26PYXC4PMMDU6'
Unexpected end of /proc/mounts line `TFQ3KGDIZ44FE:/var/lib/docker/overlay2/l/XGESBQ3AZIEWQUJ3GLTNNTGYUT:/var/lib/docker/overlay2/l/ERANPYRKYNV3DEG2ZGQ3AXWACU:/var/lib/docker/overlay2/l/P6BAVZTG34GSBSZILGZUXRGYH6:/var/lib/docker/overlay2/l/YIV34GB2LRZ2X5JC6CKMQLYHAV:/var/lib/docker/overlay2/l/N2MS6NFUCEGMZUIXD2XEJ7C6U5:/var/lib/docker/overlay2/l/VO7OOGE4H6IZE7NAQXMWDOHINZ:/var/lib/docker/overlay2/l/LSMIOCVFL5QZ63IXID2ENZYNEH:/var/lib/docker/overlay2/l/CEHVBB7QBAD3EKUNNGUSM6Q24M:/var/lib/docker/overlay2/l/6VYZTVC4FNKJDA5YQTEXL4CCPP:/var/lib/do'
Unexpected end of /proc/mounts line `overlay / overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/HDAIQ47MLSDMXA3AIGLTXG54FT:/var/lib/docker/overlay2/l/GPWJWSZ2P5DURZLTVI5OJQSLKE:/var/lib/docker/overlay2/l/IM5ZOUXU5BSZDA5VNC7B3GD4PK:/var/lib/docker/overlay2/l/LX4EBLC6QNZHKZCLHRHGWFPDTO:/var/lib/docker/overlay2/l/YDDEPDFBWDVTSSXW3ZZSOZGVAL:/var/lib/docker/overlay2/l/I74OKHDKH6AJXGAFABBW7DLEC4:/var/lib/docker/overlay2/l/WJSH46BZFHSXYWZLH5IPYZVSO6:/var/lib/docker/overlay2/l/ADRDZPKIGIK4MX54MESHPCW26D:/var/lib/docker/overlay2/l/4EMXTBHV3SVBI'
Unexpected end of /proc/mounts line `Q5PLABDWR533X:/var/lib/docker/overlay2/l/KPNEDHGXJHZXBH5YPDKHCMCCKR:/var/lib/docker/overlay2/l/WCVBIMGJZK2L4I2QA7BWOQPVQE:/var/lib/docker/overlay2/l/625QDNVKZMTN5MCPCOZC22GGRU:/var/lib/docker/overlay2/l/W6NHFX67HQ7ACHTS4ORZ2IJYCP:/var/lib/docker/overlay2/l/2HURRH7FVTC2R336TIHGAE2BGZ:/var/lib/docker/overlay2/l/DAJCTXXBGL67X23HFKPSZZG6GE:/var/lib/docker/overlay2/l/3BJBBSZ6MGHM2LWR6IDSTZB2LL:/var/lib/docker/overlay2/l/TFWVCOTXDVSZGRUZTOW7EKCICW:/var/lib/docker/overlay2/l/JH5IIIB4G62QGGVIOOKWTIIEN4:/var/lib/do'
Unexpected end of /proc/mounts line `overlay / overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/HDAIQ47MLSDMXA3AIGLTXG54FT:/var/lib/docker/overlay2/l/GPWJWSZ2P5DURZLTVI5OJQSLKE:/var/lib/docker/overlay2/l/IM5ZOUXU5BSZDA5VNC7B3GD4PK:/var/lib/docker/overlay2/l/LX4EBLC6QNZHKZCLHRHGWFPDTO:/var/lib/docker/overlay2/l/YDDEPDFBWDVTSSXW3ZZSOZGVAL:/var/lib/docker/overlay2/l/I74OKHDKH6AJXGAFABBW7DLEC4:/var/lib/docker/overlay2/l/WJSH46BZFHSXYWZLH5IPYZVSO6:/var/lib/docker/overlay2/l/ADRDZPKIGIK4MX54MESHPCW26D:/var/lib/docker/overlay2/l/4EMXTBHV3SVBI'
Unexpected end of /proc/mounts line `Q5PLABDWR533X:/var/lib/docker/overlay2/l/KPNEDHGXJHZXBH5YPDKHCMCCKR:/var/lib/docker/overlay2/l/WCVBIMGJZK2L4I2QA7BWOQPVQE:/var/lib/docker/overlay2/l/625QDNVKZMTN5MCPCOZC22GGRU:/var/lib/docker/overlay2/l/W6NHFX67HQ7ACHTS4ORZ2IJYCP:/var/lib/docker/overlay2/l/2HURRH7FVTC2R336TIHGAE2BGZ:/var/lib/docker/overlay2/l/DAJCTXXBGL67X23HFKPSZZG6GE:/var/lib/docker/overlay2/l/3BJBBSZ6MGHM2LWR6IDSTZB2LL:/var/lib/docker/overlay2/l/TFWVCOTXDVSZGRUZTOW7EKCICW:/var/lib/docker/overlay2/l/JH5IIIB4G62QGGVIOOKWTIIEN4:/var/lib/do'
paigcr-b-gpu-1011:4290:4344 [1] NCCL INFO comm 0x7f4b98274250 rank 1 nranks 4
paigcr-b-gpu-1011:4290:4344 [1] NCCL INFO NET : Using interface lo:127.0.0.1<0>
paigcr-b-gpu-1011:4290:4344 [1] NCCL INFO NET : Using interface eth0:10.151.40.239<0>
paigcr-b-gpu-1011:4290:4344 [1] NCCL INFO NET : Using interface eth1:fe80::215:5dff:fe33:ff6c%eth1<0>
paigcr-b-gpu-1011:4290:4344 [1] NCCL INFO NET/Socket : 3 interfaces found
paigcr-b-gpu-1011:4290:4344 [1] NCCL INFO Could not find real path of /sys/class/net/lo/device
paigcr-b-gpu-1011:4290:4344 [1] NCCL INFO CUDA Dev 1, IP Interfaces : lo(SOC) eth0(PXB) eth1(PXB)
paigcr-b-gpu-1012:4153:4209 [1] NCCL INFO comm 0x7f5c702a8b70 rank 3 nranks 4
paigcr-b-gpu-1012:4153:4209 [1] NCCL INFO NET : Using interface lo:127.0.0.1<0>
paigcr-b-gpu-1012:4153:4209 [1] NCCL INFO NET : Using interface eth0:10.151.40.240<0>
paigcr-b-gpu-1012:4153:4209 [1] NCCL INFO NET : Using interface eth1:fe80::215:5dff:fe33:ff6d%eth1<0>
paigcr-b-gpu-1012:4153:4209 [1] NCCL INFO NET/Socket : 3 interfaces found
paigcr-b-gpu-1011:4289:4343 [0] NCCL INFO comm 0x7fc8e824c640 rank 0 nranks 4
paigcr-b-gpu-1011:4289:4343 [0] NCCL INFO Could not find real path of /sys/class/net/lo/device
paigcr-b-gpu-1011:4289:4343 [0] NCCL INFO CUDA Dev 0, IP Interfaces : lo(SOC) eth0(PXB) eth1(PXB)
paigcr-b-gpu-1012:4152:4206 [0] NCCL INFO comm 0x7f0dc0269bf0 rank 2 nranks 4
paigcr-b-gpu-1012:4152:4206 [0] NCCL INFO NET : Using interface lo:127.0.0.1<0>
paigcr-b-gpu-1012:4152:4206 [0] NCCL INFO NET : Using interface eth0:10.151.40.240<0>
paigcr-b-gpu-1012:4152:4206 [0] NCCL INFO NET : Using interface eth1:fe80::215:5dff:fe33:ff6d%eth1<0>
paigcr-b-gpu-1012:4152:4206 [0] NCCL INFO NET/Socket : 3 interfaces found

paigcr-b-gpu-1012:4153:4209 [1] include/socket.h:361 NCCL WARN Call to connect timeout : Connection refused
paigcr-b-gpu-1012:4153:4209 [1] NCCL INFO transport/net_socket.cu:139 -> 2
paigcr-b-gpu-1012:4153:4209 [1] NCCL INFO bootstrap.cu:19 -> 2
paigcr-b-gpu-1012:4153:4209 [1] NCCL INFO bootstrap.cu:225 -> 2
paigcr-b-gpu-1012:4153:4209 [1] NCCL INFO init.cu:420 -> 2
paigcr-b-gpu-1012:4153:4209 [1] NCCL INFO init.cu:557 -> 2

paigcr-b-gpu-1012:4152:4206 [0] include/socket.h:361 NCCL WARN Call to connect timeout : Connection refused
paigcr-b-gpu-1012:4152:4206 [0] NCCL INFO transport/net_socket.cu:139 -> 2
paigcr-b-gpu-1012:4152:4206 [0] NCCL INFO bootstrap.cu:19 -> 2
paigcr-b-gpu-1012:4152:4206 [0] NCCL INFO bootstrap.cu:225 -> 2
paigcr-b-gpu-1012:4152:4206 [0] NCCL INFO init.cu:420 -> 2
paigcr-b-gpu-1012:4152:4206 [0] NCCL INFO init.cu:557 -> 2
```

I'm sure that I can ssh other servers from my main server and I also read the [running.md](https://github.com/uber/horovod/blob/master/docs/running.md).
Here is my output of `ifconfig`:
```
docker0   Link encap:Ethernet  HWaddr 02:42:1e:12:71:dd
          inet addr:172.17.0.1  Bcast:172.17.255.255  Mask:255.255.0.0
          inet6 addr: fe80::42:1eff:fe12:71dd/64 Scope:Link
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:2345145 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2011124 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:39895607789 (39.8 GB)  TX bytes:779093097 (779.0 MB)

eth0      Link encap:Ethernet  HWaddr 00:0d:3a:b7:7d:8b
          inet addr:10.151.40.239  Bcast:10.151.41.255  Mask:255.255.254.0
          inet6 addr: fe80::20d:3aff:feb7:7d8b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2715091031 errors:0 dropped:0 overruns:0 frame:0
          TX packets:435676776 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:3689427212637 (3.6 TB)  TX bytes:2386345166374 (2.3 TB)

eth1      Link encap:Ethernet  HWaddr 00:15:5d:33:ff:6c
          inet6 addr: fe80::215:5dff:fe33:ff6c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5022 errors:0 dropped:0 overruns:0 frame:0
          TX packets:245505 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:210924 (210.9 KB)  TX bytes:83508838 (83.5 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:53790608 errors:0 dropped:0 overruns:0 frame:0
          TX packets:53790608 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1091411129273 (1.0 TB)  TX bytes:1091411129273 (1.0 TB)
```

And due to running in docker, I can't use strace command.

How to solve the problem?

**Comment by qyyy** [comment]
Maybe the same problem with #281 , but in that issue, there is no solving method.

**Comment by alsrgv** [comment]
@qyyy, can you try using `-x NCCL_SOCKET_IFNAME=eth0`, since you have multiple eth NICs?

**Comment by qyyy** [comment]
Cool!!!!! It works!!!! Thank you very much @alsrgv

**Comment by lxkarthi** [comment]
I had similar issue with running multi-node job using docker. I fixed it by adding following in /etc/nccl.conf
`NCCL_SOCKET_IFNAME=^lo,docker0`
Could this be added to main Dockerfile?

**Comment by alsrgv** [comment]
@lxkarthi, this has been fixed in #700.
