### ISSUE TITLE
Segmentation Fault (11) after about 20 hours of training

### ISSUE THREAD

**Issue by maxhgerlach** [uber/horovod#585]
My Horovod trainings on a single node with 8 GPUs repeatedly crash with a segmentation fault after running for about a day (Horovod 0.14.1, Tensorflow 1.8, OpenMPI 3.1.2, libnccl 2.2.13-1+cuda9.0, Cuda 9.0).

```
[HOST:03599] *** Process received signal ***
[HOST:03599] Signal: Segmentation fault (11)
[HOST:03599] Signal code: Address not mapped (1)
[HOST:03599] Failing at address: (nil)
[HOST:03599] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7fe26f028390]
[HOST:03599] [ 1] ..../virtualenv/tf1.8_horovod_no_ofed/local/lib/python2.7/site-packages/horovod/tensorflow/mpi_lib.so(+0x34887)[0x7fe1b6d46887]
[HOST:03599] [ 2] ..../virtualenv/tf1.8_horovod_no_ofed/local/lib/python2.7/site-packages/horovod/tensorflow/mpi_lib.so(+0x366d3)[0x7fe1b6d486d3]
[HOST:03599] [ 3] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8c80)[0x7fe1ec379c80]
[HOST:03599] [ 4] /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7fe26f01e6ba]
[HOST:03599] [ 5] /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fe26ed543dd]
[HOST:03599] *** End of error message ***
```

I collected a core dump and loaded it into gdb. This is the backtrace:

```
(gdb) bt
#0  horovod::common::(anonymous namespace)::RunLoopOnce (state=..., is_coordinator=is_coordinator@entry=true) at horovod/common/operations.cc:1779
#1  0x00007f2bdf9886d3 in horovod::common::(anonymous namespace)::BackgroundThreadLoop (state=...) at horovod/common/operations.cc:1589
#2  0x00007f2c14f1bc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f2c9773a6ba in start_thread (arg=0x7f2bd77fe700) at pthread_create.c:333
#4  0x00007f2c974703dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

The backtraces for all 88 threads are here: [gist](https://gist.github.com/maxhgerlach/fd5987d66bc16cc08fff094872a978e6)

Any pointers?

**Comment by alsrgv** [comment]
@maxhgerlach, can you try upgrading to the latest Horovod (0.15.1 as of few minutes ago) and see if you can still reproduce this issue?

**Comment by maxhgerlach** [comment]
OK, I am giving 0.15.1 a try.

**Comment by alsrgv** [comment]
@wanglouis49, could you include stack trace as well?

**Comment by wanglouis49** [comment]
@alsrgv for sure. (Horovod 0.15.1, Tensorflow 1.10, OpenMPI 3.1.2, libnccl 2.2.13-1+cuda9.0, Cuda 9.0)
```
[compute008:56447] *** Process received signal ***
[compute008:56447] Signal: Segmentation fault (11)
[compute008:56447] Signal code: Address not mapped (1)
[compute008:56447] Failing at address: (nil)
[compute008:56447] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7fb944ec2390]
[compute008:56447] [ 1] /home/xxx/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so(+0x26357)[0x7fb846fa9357]
[compute008:56447] [ 2] /home/xxx/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so(+0x284cb)[0x7fb846fab4cb]
[compute008:56447] [ 3] /home/xxx/anaconda3/bin/../lib/libstdc++.so.6(+0xafc5c)[0x7fb86a4d3c5c]
[compute008:56447] [ 4] /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7fb944eb86ba]
[compute008:56447] [ 5] /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fb944bee41d]
[compute008:56447] *** End of error message ***
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 56447 on node compute008 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

**Comment by maxhgerlach** [comment]
@wanglouis49 It would probably be helpful to get a core file (run `ulimit -l unlimited` first) to analyze in a debugger. Then you could obtain source resolved stack traces. This could help pinpoint if that segmentation fault is related to the issue I have been facing.


Regarding my seg fault, so far I haven't seen it in my logs anymore. However, nodes running Horovod trainings still crash hard, causing system reboots. Some of these may be related to NFS issues, others I cannot associate to any other circumstances . Basically, I am unsure if I may just be missing error messages from my logs.

**Comment by maxhgerlach** [comment]
Now that I have resolved my unrelated crash issue, I have unfortunately run again into a segmentation fault (11) on Horovod 0.15.1:

```
[HOST:12252] *** Process received signal ***
[HOST:12252] Signal: Segmentation fault (11)
[HOST:12252] Signal code: Address not mapped (1)
[HOST:12252] Failing at address: (nil)
[HOST:12252] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f94ff5b6390]
[HOST:12252] [ 1] ..../virtualenv/tf1.8_horovod0.15.1_new_ofed/local/lib/python2.7/site-packages/horovod/tensorflow/mpi_lib.so(+0x35b87)[0x7f9447585b87]
[HOST:12252] [ 2] ..../virtualenv/tf1.8_horovod0.15.1_new_ofed/local/lib/python2.7/site-packages/horovod/tensorflow/mpi_lib.so(+0x37b2b)[0x7f9447587b2b]
[HOST:12252] [ 3] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8c80)[0x7f947cf4dc80]
[HOST:12252] [ 4] /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f94ff5ac6ba]
[HOST:12252] [ 5] /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f94ff2e23dd]
[HOST:12252] *** End of error message ***
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node HOST exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

Here is the backtrace from the core file in gdb:
```
(gdb) bt
#0  horovod::common::(anonymous namespace)::RunLoopOnce (state=..., is_coordinator=is_coordinator@entry=true) at horovod/common/operations.cc:1821
#1  0x00007f9447587b2b in horovod::common::(anonymous namespace)::BackgroundThreadLoop (state=...) at horovod/common/operations.cc:1629
#2  0x00007f947cf4dc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f94ff5ac6ba in start_thread (arg=0x7f943f7fe700) at pthread_create.c:333
#4  0x00007f94ff2e23dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```
This now points to a [different line](https://github.com/uber/horovod/blob/4370712514dbd9940062069d212468a1deb2efbe/horovod/common/operations.cc#L1821) than in the original post in this issue.

Here is the output from [(gdb) thread apply all backtrace](https://gist.github.com/maxhgerlach/a0670f303f2872b1f6a8210ad08905d0).

@alsrgv Does this help with pinpointing the issue?

**Comment by maxhgerlach** [comment]
I looked a bit more closely at the core-file in gdb. `new_entry.tensor` is in fact a null shared_ptr, so accessing it must have caused the segmentation fault:

```
(gdb) list
1816
1817	        while (!responses.empty()) {
1818	          auto new_response = responses.front();
1819	          assert(new_response.tensor_names().size() == 1);
1820	          auto& new_entry = state.tensor_table[new_response.tensor_names()[0]];
1821	          int64_t new_tensor_size = new_entry.tensor->size();
1822
1823	          if (response.response_type() == new_response.response_type() &&
1824	              response.devices() == new_response.devices() &&
1825	              entry.tensor->dtype() == new_entry.tensor->dtype() &&
(gdb) new_entry
Undefined command: "new_entry".  Try "help".
(gdb) p new_entry
$1 = (horovod::common::(anonymous namespace)::TensorTableEntry &) @0x7f94203a9230: {tensor_name = "", context = std::shared_ptr (empty) 0x0, tensor = std::shared_ptr (empty) 0x0,
  output = std::shared_ptr (empty) 0x0, root_rank = 0, ready_event = std::shared_ptr (empty) 0x0, device = -1,
  callback = {<std::_Maybe_unary_or_binary_function<void, horovod::common::Status const&>> = {<std::unary_function<horovod::common::Status const&, void>> = {<No data fields>}, <No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x0, _M_const_object = 0x0, _M_function_pointer = 0x0, _M_member_pointer = NULL},
        _M_pod_data = '\000' <repeats 15 times>}, _M_manager = 0x0}, _M_invoker = 0x0}}
(gdb) p new_entry.tensor
$2 = std::shared_ptr (empty) 0x0
(gdb) p new_response
$3 = {response_type_ = horovod::common::MPIResponse::ALLREDUCE, tensor_names_ = std::vector of length 1, capacity 1 = {
    "Optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllreduce_Optimizer_gradients_Bucket0_Decoder_Layer5_Sublayer1_Attention_encoder_attention_result_matmul_grad_tuple_control_dependency_1_0"}, error_message_ = "", devices_ = std::vector of length 8, capacity 8 = {0, 1, 2, 3, 4, 5, 6, 7}, tensor_sizes_ = std::vector of length 0, capacity 0}
```
The tensor that is referenced in `new_response` is of shape:[1, 1024, 1024].

**Comment by alsrgv** [comment]
@maxhgerlach, thanks for the detailed investigation!  After staring at the code for a while I've discovered a potential race in access to `horovod_global.tensor_table`. Could you try installing from the branch `fix_tensor_table_race` and see if the issue goes away?

```
$ [flags] pip install git+https://github.com/uber/horovod@fix_tensor_table_race
```

**Comment by maxhgerlach** [comment]
@alsrgv, great, that may very well be the culprit. Thanks! I'll run from the branch `fix_tensor_table_race` from now on and report back in case the issue resurfaces. 

For what it's worth, I haven't seen it in the 3+ days that have passed since I collected that core dump.

**Comment by alsrgv** [comment]
I'll land #619 and close this issue.  Please let me know if it resurfaces.
