### ISSUE TITLE
Spawning two processes on one GPU

### ISSUE THREAD

**Issue by goru97** [uber/horovod#590]
Hi team,
I am training my model using Horovod. The cluster is composed of four nodes, two nodes with 8 GPUs and other two with 4 GPUs. 

Command to run training:
```
mpirun --allow-run-as-root -np 24 -H host1:4,host24,host3:8,host4:8 --allow-run-as-root -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x HOROVOD_MPI_THREADS_DISABLE=1 -x LD_LIBRARY_PATH -x PATH -x NCCL_SOCKET_IFNAME=eth0 --mca pml ob1 --mca btl self,tcp --mca plm_rsh_args "-p 12345" --mca oob_tcp_if_include eth0 --mca btl_tcp_if_exclude lo,docker0 python train_hvd.py coco ../coco/
```
It works fine with two nodes each having 4 GPUs. Also with two nodes each having 8 GPUs. The combination, four nodes with 24 GPUs gives resource exhaustion error (OOM).
When I ran `nvidia-smi` on one of the nodes with 4GPUs, it showed that horovod is trying to run 8 processes on that node. Here's the output of that. Do you think that could be the problem and if you could please suggest how to mitigate that.

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.44                 Driver Version: 396.44                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:1B.0 Off |                    0 |
| N/A   55C    P0    66W / 300W |  16159MiB / 16160MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:00:1C.0 Off |                    0 |
| N/A   48C    P0    61W / 300W |  12551MiB / 16160MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:00:1D.0 Off |                    0 |
| N/A   50C    P0    65W / 300W |  16159MiB / 16160MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   62C    P0    77W / 300W |  16159MiB / 16160MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     23944      C   python                                     15622MiB |
|    0     39627      C   python                                       524MiB |
|    1     23945      C   python                                     11002MiB |
|    1     39628      C   python                                      1534MiB |
|    2     23946      C   python                                     15622MiB |
|    2     39629      C   python                                       524MiB |
|    3     23947      C   python                                     15622MiB |
|    3     39630      C   python                                       524MiB |
+-----------------------------------------------------------------------------+
```

**Comment by tgaddair** [comment]
Hey @goru97, if you're seeing 8 processes on a machine with only 4 GPUs, it comes back to the `mpirun` command.  It looks like there's a typo in the command you provided:

```
mpirun --allow-run-as-root -np 24 -H host1:4,host24,host3:8,host4:8 ...
```

There should be a colon between "host2" and "4", is it possible there's a similar typo in the command you ran, or you're specifying "hostX:8" when hostX only has 4 GPUs?

**Comment by goru97** [comment]
Hi @tgaddair, I replaced the IP addresses with `hostx:gpus` and made error while typing. No, the actual command looks correct and has the right number of gpus assigned, based on the host.

**Comment by alsrgv** [comment]
@goru97, is it possible that you have zombie processes?  Can you survey your hosts and kill off any training processes that should not be there?

**Comment by goru97** [comment]
@alsrgv I stopped the training and looked at the number of processes on the hosts with 4 GPUs, there was no zombie process consuming any GPU.

**Comment by goru97** [comment]
@alsrgv You were right about the zombie process. It is working now.
