### ISSUE TITLE
horovod hangs with multi gpus on one machine

### ISSUE THREAD

**Issue by duohappy** [uber/horovod#638]
I read many issues about the problem, but I can not solve it. 

# system
os: ubuntu 16.04 lts
openmpi: 3.1.3
cuda: 9.0
nccl: 2.3
horovod: 0.15.1

I use tensorflow, and I have 6 GPUs on one machine.

# ifconfig
docker0   Link encap:以太网  硬件地址 02:42:c6:0b:ab:bc  
          inet 地址:172.17.0.1  广播:0.0.0.0  掩码:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  跃点数:1
          接收数据包:0 错误:0 丢弃:0 过载:0 帧数:0
          发送数据包:0 错误:0 丢弃:0 过载:0 载波:0
          碰撞:0 发送队列长度:0 
          接收字节:0 (0.0 B)  发送字节:0 (0.0 B)

enp129s0f0 Link encap:以太网  硬件地址 ac:1f:6b:92:85:66  
          inet 地址:192.168.8.100  广播:192.168.8.255  掩码:255.255.255.0
          inet6 地址: 2408:84e2:104:2808:f8d9:faaa:1ce4:bf37/64 Scope:Global
          inet6 地址: fe80::ca36:fa0f:16c6:d579/64 Scope:Link
          inet6 地址: 2408:84e2:104:2808:ec89:141c:7a8c:2/128 Scope:Global
          inet6 地址: 2408:84e2:104:2808:c86b:be43:9422:e4d8/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  跃点数:1
          接收数据包:49778418 错误:0 丢弃:0 过载:0 帧数:0
          发送数据包:106502616 错误:0 丢弃:0 过载:0 载波:0
          碰撞:0 发送队列长度:1000 
          接收字节:20831525538 (20.8 GB)  发送字节:143721308272 (143.7 GB)
          Memory:fb520000-fb53ffff 

enp129s0f1 Link encap:以太网  硬件地址 ac:1f:6b:92:85:67  
          UP BROADCAST MULTICAST  MTU:1500  跃点数:1
          接收数据包:0 错误:0 丢弃:0 过载:0 帧数:0
          发送数据包:0 错误:0 丢弃:0 过载:0 载波:0
          碰撞:0 发送队列长度:1000 
          接收字节:0 (0.0 B)  发送字节:0 (0.0 B)
          Memory:fb500000-fb51ffff 

ens1f0    Link encap:以太网  硬件地址 a0:36:9f:7b:28:f4  
          UP BROADCAST MULTICAST  MTU:1500  跃点数:1
          接收数据包:0 错误:0 丢弃:0 过载:0 帧数:0
          发送数据包:0 错误:0 丢弃:0 过载:0 载波:0
          碰撞:0 发送队列长度:1000 
          接收字节:0 (0.0 B)  发送字节:0 (0.0 B)

ens1f1    Link encap:以太网  硬件地址 a0:36:9f:7b:28:f6  
          UP BROADCAST MULTICAST  MTU:1500  跃点数:1
          接收数据包:0 错误:0 丢弃:0 过载:0 帧数:0
          发送数据包:0 错误:0 丢弃:0 过载:0 载波:0
          碰撞:0 发送队列长度:1000 
          接收字节:0 (0.0 B)  发送字节:0 (0.0 B)

lo        Link encap:本地环回  
          inet 地址:127.0.0.1  掩码:255.0.0.0
          inet6 地址: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  跃点数:1
          接收数据包:13596278 错误:0 丢弃:0 过载:0 帧数:0
          发送数据包:13596278 错误:0 丢弃:0 过载:0 载波:0
          碰撞:0 发送队列长度:1000 
          接收字节:134089183965 (134.0 GB)  发送字节:134089183965 (134.0 GB)

# test keras simple example
I download the code from [https://github.com/uber/horovod/blob/master/examples/keras_mnist.py](https://github.com/uber/horovod/blob/master/examples/keras_mnist.py), and just change the filename.

# one GPU
It is fine, if I run the code as follow.
python keras_simple_distribute_train.py

## mpirun command
mpirun -np 4 \
 -H localhost:4 \
 -bind-to none -map-by slot \
 -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
 -x NCCL_SOCKET_IFNAME=enp129s0f0 \
 -x NCCL_P2P_DISABLE=1 \
 -mca pml ob1 -mca btl ^openib \
 -mca btl_tcp_if_exclude lo,docker0,enp129s0f1,ens1f0,ens1f1 \
 python keras_simple_distribute_train.py

it cannot start train.

## strace command
strace mpirun -np 4  -H localhost:4  -bind-to none -map-by slot  -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH  -x NCCL_SOCKET_IFNAME=enp129s0f0  -x NCCL_P2P_DISABLE=1  -mca pml ob1 -mca btl ^openib  -mca btl_tcp_if_exclude lo,docker0,enp129s0f1,ens1f0,ens1f1  python keras_simple_distribute_train.py > keras_dist.txt 2>&1

gist: [https://gist.github.com/duohappy/ce9460298bbf25e95c49ebf28f29e1d8](https://gist.github.com/duohappy/ce9460298bbf25e95c49ebf28f29e1d8)

### nvidia-smi:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.145                Driver Version: 384.145                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:05:00.0 Off |                    0 |
| N/A   41C    P0    37W / 250W |    978MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  Off  | 00000000:08:00.0 Off |                    0 |
| N/A   40C    P0    38W / 250W |    552MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-PCIE...  Off  | 00000000:09:00.0 Off |                    0 |
| N/A   41C    P0    37W / 250W |    552MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-PCIE...  Off  | 00000000:84:00.0 Off |                    0 |
| N/A   40C    P0    37W / 250W |    552MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-PCIE...  Off  | 00000000:88:00.0 Off |                    0 |
| N/A   33C    P0    24W / 250W |     10MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla V100-PCIE...  Off  | 00000000:89:00.0 Off |                    0 |
| N/A   35C    P0    24W / 250W |     10MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1661      C   /usr/bin/python                              426MiB |
|    0     33001      C   python                                       542MiB |
|    1     33002      C   python                                       542MiB |
|    2     33003      C   python                                       542MiB |
|    3     33004      C   python                                       542MiB |
+-----------------------------------------------------------------------------+

### ps aux | grep zhouwen
zhouwen+ 33001  100  0.2 38197220 1197616 pts/8 Sl  13:07  18:23 python keras_simple_distribute_train.py
zhouwen+ 33002  100  0.2 38227940 1231340 pts/8 Sl  13:07  18:23 python keras_simple_distribute_train.py
zhouwen+ 33003  100  0.2 38229984 1230860 pts/8 Sl  13:07  18:23 python keras_simple_distribute_train.py
zhouwen+ 33004  100  0.2 38229980 1230556 pts/8 Sl  13:07  18:24 python keras_simple_distribute_train.py

**Comment by jeff-engineml** [comment]
Downgrading to mpi 3.0.0 seems to have worked for me

**Comment by duohappy** [comment]
> Downgrading to mpi 3.0.0 seems to have worked for me

@jeff-engineml ,:+1:, thank you very much. Everything is fine. :)

**Comment by alsrgv** [comment]
@duohappy, @jeff-engineml, could you guys try recently released Open MPI 4.0.0 and see if it works better for you?

**Comment by duohappy** [comment]
> @duohappy, @jeff-engineml, could you guys try recently released Open MPI 4.0.0 and see if it works better for you?

@alsrgv, I try Open MPI 4.0.0 just now，and it also works for me.

Open MPI 3.0.0 :white_check_mark:
Open MPI 3.1.3 :x:
Open MPI 4.0.0 :white_check_mark:

**Comment by alsrgv** [comment]
@duohappy, thanks for your report!  We'll be planning upgrade to Open MPI 4.0.0 in our Dockerfile.

**Comment by duohappy** [comment]
@alsrgv, this repo is amazing, and I am very grateful to you, :+1:

**Comment by jackalcooper** [comment]
Same problem here. Maybe it is a good idea to put a notice telling people Open MPI 3.1.3 might lead to tensorflow hanging there.

**Comment by alsrgv** [comment]
Good idea. Opened #729.
