### ISSUE TITLE
"WARN Connection closed by remote peer " or  "NCCL WARN Call to connect timeout : Connection refused" and freeze

### ISSUE THREAD

**Issue by LEESEYUN** [uber/horovod#666]
When I run the example code (examples/ tensorflow_mnist_estimator.py), it prints "WARN Connection closed by remote peer " or  "NCCL WARN Call to connect timeout : Connection refused" and freeze.

-------------------------------------------------------------------------------------------------------------------------------
mpirun -np 8 -hostfile seyun_hostind-to none -map-by slot -x NCCL_DEBUG=INFO -mca btl_tcp_if_exclude lo,eno1 -x NCCL_SOCKET_IFNAME=eth0,eno2 python3 tensorflow_mnist_estimator.py 
-------------------------------------------------------------------------------------------------------------------------------
Also I try to add option "btl_tcp_if_include".  
Public key is on both server. 
clients:   - GPU                            - 4 
              -network interface name - eth0           [lo]
server:    -GPU                            - 4
               -network interface name - eno2         [eno1,lo]

this is the output log of NCCL_DEBUG

============================================================================
 seyun:17280:17553 [0] INFO NET : Using interface eth0:115.145.178.160<0>
seyun:17280:17553 [0] INFO NET/IB : Using interface eth0 for sideband communication
seyun:17280:17553 [0] INFO Using internal Network Socket
seyun:17280:17553 [0] INFO Using NCCL Low-latency algorithm for sizes below 16384
seyun:17280:17553 [0] INFO NET : Using interface eth0:115.145.178.160<0>
seyun:17280:17553 [0] INFO NET/Socket : 1 interfaces found
NCCL version 2.2.12+cuda9.0
seyun:17281:17552 [1] INFO NET : Using interface eth0:115.145.178.160<0>
seyun:17281:17552 [1] INFO NET/IB : Using interface eth0 for sideband communication
seyun:17281:17552 [1] INFO Using internal Network Socket
seyun:17281:17552 [1] INFO Using NCCL Low-latency algorithm for sizes below 16384
seyun:17282:17546 [2] INFO NET : Using interface eth0:115.145.178.160<0>
seyun:17282:17546 [2] INFO NET/IB : Using interface eth0 for sideband communication
seyun:17282:17546 [2] INFO Using internal Network Socket
seyun:17282:17546 [2] INFO Using NCCL Low-latency algorithm for sizes below 16384
seyun:17283:17549 [3] INFO NET : Using interface eth0:115.145.178.160<0>
seyun:17283:17549 [3] INFO NET/IB : Using interface eth0 for sideband communication
seyun:17283:17549 [3] INFO Using internal Network Socket
seyun:17283:17549 [3] INFO Using NCCL Low-latency algorithm for sizes below 16384
vclab-server-08:27376:27548 [0] NCCL INFO NET : Using interface eno2:115.145.173.234<0>
vclab-server-08:27376:27548 [0] NCCL INFO NET/IB : Using interface eno2 for sideband communication
vclab-server-08:27376:27548 [0] NCCL INFO Using internal Network Socket
vclab-server-08:27376:27548 [0] NCCL INFO rank 4 nranks 8
vclab-server-08:27377:27554 [1] NCCL INFO NET : Using interface eno2:115.145.173.234<0>
vclab-server-08:27377:27554 [1] NCCL INFO NET/IB : Using interface eno2 for sideband communication
vclab-server-08:27377:27554 [1] NCCL INFO Using internal Network Socket
vclab-server-08:27377:27554 [1] NCCL INFO rank 5 nranks 8
vclab-server-08:27378:27555 [2] NCCL INFO NET : Using interface eno2:115.145.173.234<0>
vclab-server-08:27378:27555 [2] NCCL INFO NET/IB : Using interface eno2 for sideband communication
vclab-server-08:27378:27555 [2] NCCL INFO Using internal Network Socket
vclab-server-08:27378:27555 [2] NCCL INFO rank 6 nranks 8
vclab-server-08:27379:27549 [3] NCCL INFO NET : Using interface eno2:115.145.173.234<0>
vclab-server-08:27379:27549 [3] NCCL INFO NET/IB : Using interface eno2 for sideband communication
vclab-server-08:27379:27549 [3] NCCL INFO Using internal Network Socket
vclab-server-08:27379:27549 [3] NCCL INFO rank 7 nranks 8
seyun:17280:17553 [0] INFO comm 0x7f5fc83281a0 rank 0 nranks 8
seyun:17281:17552 [1] INFO comm 0x7fc84c354fe0 rank 1 nranks 8
seyun:17281:17552 [1] INFO NET : Using interface eth0:115.145.178.160<0>
seyun:17281:17552 [1] INFO NET/Socket : 1 interfaces found
seyun:17283:17549 [3] INFO comm 0x7fa1f035cfe0 rank 3 nranks 8
seyun:17283:17549 [3] INFO NET : Using interface eth0:115.145.178.160<0>
seyun:17283:17549 [3] INFO NET/Socket : 1 interfaces found
seyun:17282:17546 [2] INFO comm 0x7f777035d990 rank 2 nranks 8
seyun:17282:17546 [2] INFO NET : Using interface eth0:115.145.178.160<0>
seyun:17282:17546 [2] INFO NET/Socket : 1 interfaces found
vclab-server-08:27376:27548 [0] NCCL INFO comm 0x7f915844e4b0 rank 4 nranks 8
vclab-server-08:27376:27548 [0] NCCL INFO NET : Using interface eno2:115.145.173.234<0>
vclab-server-08:27376:27548 [0] NCCL INFO NET/Socket : 1 interfaces found

seyun:17280:17952 [0] transport/net_socket.cu:168 WARN Message truncated : received 136 bytes instead of 72

seyun:17280:17952 [0] INFO bootstrap.cu:45 -> 3 [Net]
seyun:17280:17952 [0] INFO bootstrap.cu:102 -> 2 [bthread]

seyun:17280:17553 [0] include/socket.h:371 WARN Connection closed by remote peer

seyun:17281:17552 [1] include/socket.h:371 WARN Connection closed by remote peer

seyun:17282:17546 [2] include/socket.h:371 WARN Connection closed by remote peer
seyun:17280:17553 [0] INFO transport/net_socket.cu:166 -> 2
seyun:17280:17553 [0] INFO bootstrap.cu:45 -> 2 [Net]
seyun:17280:17553 [0] INFO bootstrap.cu:259 -> 2
seyun:17280:17553 [0] INFO init.cu:413 -> 2
seyun:17280:17553 [0] INFO init.cu:536 -> 2
seyun:17282:17546 [2] INFO transport/net_socket.cu:166 -> 2
seyun:17282:17546 [2] INFO bootstrap.cu:45 -> 2 [Net]
seyun:17282:17546 [2] INFO bootstrap.cu:259 -> 2

seyun:17283:17549 [3] include/socket.h:371 WARN Connection closed by remote peer
seyun:17283:17549 [3] INFO transport/net_socket.cu:166 -> 2
seyun:17281:17552 [1] INFO transport/net_socket.cu:166 -> 2
seyun:17281:17552 [1] INFO bootstrap.cu:45 -> 2 [Net]
seyun:17281:17552 [1] INFO bootstrap.cu:259 -> 2
seyun:17281:17552 [1] INFO init.cu:413 -> 2
seyun:17282:17546 [2] INFO init.cu:413 -> 2
seyun:17282:17546 [2] INFO init.cu:536 -> 2
seyun:17283:17549 [3] INFO bootstrap.cu:45 -> 2 [Net]
seyun:17283:17549 [3] INFO bootstrap.cu:259 -> 2
seyun:17283:17549 [3] INFO init.cu:413 -> 2
seyun:17283:17549 [3] INFO init.cu:536 -> 2
seyun:17281:17552 [1] INFO init.cu:536 -> 2
vclab-server-08:27377:27554 [1] NCCL INFO comm 0x7f6764444df0 rank 5 nranks 8
vclab-server-08:27379:27549 [3] NCCL INFO comm 0x7f334840d830 rank 7 nranks 8
vclab-server-08:27378:27555 [2] NCCL INFO comm 0x7f44fc446140 rank 6 nranks 8
vclab-server-08:27377:27554 [1] NCCL INFO NET : Using interface eno2:115.145.173.234<0>
vclab-server-08:27377:27554 [1] NCCL INFO NET/Socket : 1 interfaces found
vclab-server-08:27379:27549 [3] NCCL INFO NET : Using interface eno2:115.145.173.234<0>
vclab-server-08:27379:27549 [3] NCCL INFO NET/Socket : 1 interfaces found
vclab-server-08:27378:27555 [2] NCCL INFO NET : Using interface eno2:115.145.173.234<0>
vclab-server-08:27378:27555 [2] NCCL INFO NET/Socket : 1 interfaces found

vclab-server-08:27379:27549 [3] include/socket.h:369 NCCL WARN Call to connect timeout : Connection refused
vclab-server-08:27379:27549 [3] NCCL INFO transport/net_socket.cu:138 -> 2
vclab-server-08:27379:27549 [3] NCCL INFO bootstrap.cu:19 -> 2
vclab-server-08:27379:27549 [3] NCCL INFO bootstrap.cu:195 -> 2
vclab-server-08:27379:27549 [3] NCCL INFO init.cu:446 -> 2
vclab-server-08:27379:27549 [3] NCCL INFO init.cu:593 -> 2

vclab-server-08:27378:27555 [2] include/socket.h:369 NCCL WARN Call to connect timeout : Connection refused
vclab-server-08:27378:27555 [2] NCCL INFO transport/net_socket.cu:138 -> 2
vclab-server-08:27378:27555 [2] NCCL INFO bootstrap.cu:19 -> 2
vclab-server-08:27378:27555 [2] NCCL INFO bootstrap.cu:195 -> 2
vclab-server-08:27378:27555 [2] NCCL INFO init.cu:446 -> 2
vclab-server-08:27378:27555 [2] NCCL INFO init.cu:593 -> 2

vclab-server-08:27377:27554 [1] include/socket.h:369 NCCL WARN Call to connect timeout : Connection refused
vclab-server-08:27377:27554 [1] NCCL INFO transport/net_socket.cu:138 -> 2
vclab-server-08:27377:27554 [1] NCCL INFO bootstrap.cu:19 -> 2
vclab-server-08:27377:27554 [1] NCCL INFO bootstrap.cu:195 -> 2
vclab-server-08:27377:27554 [1] NCCL INFO init.cu:446 -> 2
vclab-server-08:27377:27554 [1] NCCL INFO init.cu:593 -> 2
============================================================================

Thank you for your reply !

**Comment by tgaddair** [comment]
Hey @LEESEYUN, can you share the output of running `ifconfig` (see [running.md](https://github.com/uber/horovod/blob/master/docs/running.md))?  Based on your command above, you may want to try `-x NCCL_SOCKET_IFNAME=^eno1,eth0,eno2

**Comment by LEESEYUN** [comment]
@tgaddair Thank you for your reply 

Here is my clients com

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 115.145.178.160  netmask 255.255.255.0  broadcast 115.145.178.255
        inet6 fe80::5f2f:4cb7:eca7:2be  prefixlen 64  scopeid 0x20<link>
        ether fc:aa:14:79:64:fe  txqueuelen 1000  (Ethernet)
        RX packets 42154  bytes 26484468 (26.4 MB)
        RX errors 0  dropped 3435  overruns 0  frame 0
        TX packets 6879  bytes 858994 (858.9 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 809  bytes 73987 (73.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 809  bytes 73987 (73.9 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

This is my server com

eno1      Link encap:Ethernet  HWaddr ac:1f:6b:80:f2:e4  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Memory:fb120000-fb13ffff 

eno2      Link encap:Ethernet  HWaddr ac:1f:6b:80:f2:e5  
          inet addr:115.145.173.234  Bcast:115.145.173.255  Mask:255.255.255.0
          inet6 addr: fe80::df2c:516c:8492:a937/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5726047 errors:0 dropped:4 overruns:0 frame:0
          TX packets:4942968 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2782579422 (2.7 GB)  TX bytes:2732983272 (2.7 GB)
          Memory:fb100000-fb11ffff 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:110225 errors:0 dropped:0 overruns:0 frame:0
          TX packets:110225 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:24465806 (24.4 MB)  TX bytes:24465806 (24.4 MB)

I try to NCCL_SOCKET_IFNAME or btl_tcp_if_exclude ,btl_tcp_if_include option, but it show the samething.

Thank you for your reply

**Comment by LEESEYUN** [comment]
I solve this problem . Thank you!!

**Comment by tgaddair** [comment]
That's great to hear, @LEESEYUN!  Would you mind sharing how you were able to solve the issue?

**Comment by tingweiwu** [comment]
@LEESEYUN I meeting the same issue when I run  `uber/horovod:0.15.2-tf1.12.0-torch1.0.0-py3.5`.
but go well when with the verison `uber/horovod:0.13.10-tf1.9.0-torch0.4.0-py3.5`
 how did you solve it?

**Comment by alsrgv** [comment]
@tingweiwu, can you share the output of `ifconfig`?  What `mpirun` command are you using?

**Comment by purnasanyal** [comment]
@LEESEYUN , I am getting the same error , how did you fix that

**Comment by tingweiwu** [comment]
@alsrgv it have been solved by [uber/horovod#700 (comment)](https://github.com/uber/horovod/pull/700#issuecomment-446851794)

**Comment by purnasanyal** [comment]
@tingweiwu I tried using NCCL_SOCKET_IFNAME=^docker0    , but that did not work
DO I need to do anything else?

**Comment by alsrgv** [comment]
@purnasanyal, with latest NCCL, you should be setting `NCCL_SOCKET_IFNAME=^docker0,lo`, or simply setting `NCCL_SOCKET_IFNAME=<your routable interface>`.
