### ISSUE TITLE
Horovod hangs on multi-machine keras program test

### ISSUE THREAD

**Issue by Yang-HangWA** [uber/horovod#669]
machine A:user1(not root)
machine B:user2 (not root)
My data and program on machine A,then I can ssh to machine B without password.
when I run:
`mpirun -np 4 -H localhost:2,server_two:2 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x NCCL_IB_DISABLE=1  -mca pml ob1 python src/train.py 
`
Nothing happened.
It works fine if I only run the program on machine A. Do I need to copy the data and program to machine B？ Or there is something I have missed?

**Comment by tgaddair** [comment]
Hey @Yang-HangWA, yes, the script should be available on all machines at the same absolute path (a networked filesystem helps with this).  Same goes for the data.  Please give that a shot, and let me know if that helps solve the issue.

**Comment by Yang-HangWA** [comment]
@tgaddair Thanks for your help. After I install openmpi nccl and horovod on machine B , i run the keras_mnist_advanced.py on localhost and  I meet another problem. Horovod hangs!
![keras_hang](https://user-images.githubusercontent.com/38546249/49326054-3ac24380-f587-11e8-91d4-6254afdf2e90.PNG)

**Comment by tgaddair** [comment]
Hey @Yang-HangWA, you specified `-np 2` but then requested `-H localhost:4`.  Could you try with `-H localhost:2` instead?

**Comment by Yang-HangWA** [comment]
It hangs too. I run the same command on machine A which runs with no problem.I was really confused.
Run on machine B:
![np_2](https://user-images.githubusercontent.com/38546249/49349435-8d197680-f6e5-11e8-90a0-6a8a47712392.PNG)
Run on machine A:
![nomal_a](https://user-images.githubusercontent.com/38546249/49349590-4aa46980-f6e6-11e8-921d-6b40b48eae60.PNG)

**Comment by Yang-HangWA** [comment]
@tgaddair  Thanks again. I find the problem caused by different version of open mpi.I use openmpi-4.0.0 on machine A and openmpi-3.1.3 on machine B.When I changed  version of the openmpi，the problem solved.So I think the openmpi-4.0.0 may solved the problem.
But I run
`mpirun -np 4 -H machine_A:2,machine_B:2 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x NCCL_IB_DISABLE=1 -mca pml ob1 python src/train.py ` 
It hangs with info:
I [ml2][[44855,1],2][btl_tcp_endpoint.c:626:mca_btl_tcp_endpoint_recv_connect_ack] received unexpected process identifier [[44855,1],3]

**Comment by Yang-HangWA** [comment]
When I run 
`mpirun -np 4 -H 10.91.42.95:2,10.91.42.96:2 -bind-to none -map-by slot -x NCCL_DEBUG=ERROR -x NCCL_IB_DISABLE=1 -x LD_LIBRARY_PATH -x PATH -mca pml ob1 python /home/yanghang/horovod/examples/keras_mnist_advanced.py`
It hangs with info:
`--------------------------------------------------------------------------
WARNING: Open MPI accepted a TCP connection from what appears to be a
another Open MPI process but cannot find a corresponding process
entry for that peer.

This attempted connection will be ignored; your MPI job may or may not
continue properly.

  Local host: ml2
  PID:        18684
--------------------------------------------------------------------------
`
I think it's also caused by open mpi. I'm trying to solve this.

**Comment by Yang-HangWA** [comment]
I use another machine to test this.The command as follow:
`mpirun -np 4 -H machine_A:2,machine_C:2 -bind-to none -map-by slot -x NCCL_DEBUG=ERROR -x NCCL_IB_DISABLE=1 -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python /home/yanghang/horovod/examples/keras_mnist_advanced.py`
It seems something else wrong.
`2018-12-03 19:26:34.980094: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10405 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:04:00.0, compute capability: 6.1)
x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
Epoch 1/24
Epoch 1/24
Epoch 1/24
Epoch 1/24
Using TensorFlow backend.
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/yanghang/horovod/examples/keras_mnist_advanced.py", line 122, in <module>
    validation_steps=3 * test_batches // hvd.size())
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Mismatched ALLREDUCE CPU/GPU device selection: One rank specified device GPU, but another rank specified device CPU.
	 [[{{node training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_dense_2_MatMul_grad_MatMul_1_0}} = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](training/Adadelta/gradients/dense_2/MatMul_grad/MatMul_1/_229)]]
Traceback (most recent call last):
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Mismatched ALLREDUCE CPU/GPU device selection: One rank specified device GPU, but another rank specified device CPU.
	 [[{{node training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_dense_2_MatMul_grad_MatMul_1_0}} = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adadelta/gradients/dense_2/MatMul_grad/MatMul_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanghang/horovod/examples/keras_mnist_advanced.py", line 122, in <module>
    validation_steps=3 * test_batches // hvd.size())
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/models.py", line 1223, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 2096, in fit_generator
    class_weight=class_weight)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 1814, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2352, in __call__
    **self.session_kwargs)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Mismatched ALLREDUCE CPU/GPU device selection: One rank specified device GPU, but another rank specified device CPU.
	 [[node training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_dense_2_MatMul_grad_MatMul_1_0 (defined at <string>:51)  = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adadelta/gradients/dense_2/MatMul_grad/MatMul_1)]]

Caused by op 'training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_dense_2_MatMul_grad_MatMul_1_0', defined at:
  File "/home/yanghang/horovod/examples/keras_mnist_advanced.py", line 122, in <module>
    validation_steps=3 * test_batches // hvd.size())
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/models.py", line 1223, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 1978, in fit_generator
    self._make_train_function()
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 990, in _make_train_function
    loss=self.total_loss)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/optimizers.py", line 344, in get_updates
    grads = self.get_gradients(loss, params)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/horovod/_keras/__init__.py", line 55, in get_gradients
    compression=self._compression)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/horovod/tensorflow/__init__.py", line 83, in allreduce
    summed_tensor_compressed = _allreduce(tensor_compressed)
  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/horovod/tensorflow/mpi_ops.py", line 90, in _allreduce
    return MPI_LIB.horovod_allreduce(tensor, name=name)
  File "<string>", line 51, in horovod_allreduce
 .....
` 
When I run my program to train,I met another problem.The command as follow:
 `mpirun -np 4 -H machine_A:2,machine_C:2 -bind-to none -map-by slot -x NCCL_DEBUG=ERROR -x NCCL_IB_DISABLE=1 -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python /home/yanghang/temp_code/train.py`
The message not the same,the program hangs with info:
`Train on 1884 data, test on 209 data
Train on 1884 data, test on 209 data
Train on 1884 data, test on 209 data
Train on 1884 data, test on 209 data
Epoch 1/9
Epoch 1/9
Epoch 1/9
Epoch 1/9
WARNING: One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
Stalled ops:
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllgather_training_Adadelta_gradients_embedding_1_embedding_lookup_grad_Reshape_0 [missing ranks: 0, 1, 2]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllgather_training_Adadelta_gradients_embedding_1_embedding_lookup_grad_Reshape_1_0 [missing ranks: 0, 1]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllgather_training_Adadelta_gradients_embedding_1_GatherV2_grad_Reshape_0 [missing ranks: 2, 3]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_conv1d_1_convolution_ExpandDims_1_grad_Reshape_0 [missing ranks: 2]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_conv1d_2_convolution_ExpandDims_1_grad_Reshape_0 [missing ranks: 2]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_conv1d_2_Reshape_grad_Reshape_0 [missing ranks: 2]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_conv1d_1_Reshape_grad_Reshape_0 [missing ranks: 2]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_conv1d_3_convolution_ExpandDims_1_grad_Reshape_0 [missing ranks: 2]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllgather_training_Adadelta_gradients_embedding_1_GatherV2_grad_Reshape_1_0 [missing ranks: 2, 3]
WARNING: One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
Stalled ops:
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllgather_training_Adadelta_gradients_embedding_1_embedding_lookup_grad_Reshape_0 [missing ranks: 0, 1, 2]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllgather_training_Adadelta_gradients_embedding_1_embedding_lookup_grad_Reshape_1_0 [missing ranks: 0, 1]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllgather_training_Adadelta_gradients_embedding_1_GatherV2_grad_Reshape_0 [missing ranks: 2, 3]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_conv1d_1_convolution_ExpandDims_1_grad_Reshape_0 [missing ranks: 2]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_conv1d_2_convolution_ExpandDims_1_grad_Reshape_0 [missing ranks: 2]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_conv1d_2_Reshape_grad_Reshape_0 [missing ranks: 2]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_conv1d_1_Reshape_grad_Reshape_0 [missing ranks: 2]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_conv1d_3_convolution_ExpandDims_1_grad_Reshape_0 [missing ranks: 2]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllgather_training_Adadelta_gradients_embedding_1_GatherV2_grad_Reshape_1_0 [missing ranks: 2, 3]
WARNING: One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
`

**Comment by tgaddair** [comment]
Looks like there may be more config issues with machine C.  We should also focus on getting the example code to work first, as there may be a bug in your training script.

The issue between machines A and B may be due to [non-routed network interfaces](https://github.com/uber/horovod/blob/master/docs/running.md#hangs-due-to-non-routed-network-interfaces).  Could you try running `ifconfig` on each machine and paste the results here?

For more info on the error you're seeing, I suggest take a look at [this](https://github.com/open-mpi/ompi/issues/5808) OpenMPI issue.

As for the issue you're seeing on machine C, I suggest taking a look at #398.

**Comment by Yang-HangWA** [comment]
@tgaddair  Thank you very much. The issue between machines A and B have solved when I use  `-mca btl_tcp_if_exclude <interface>` .
But I can't solve `FailedPreconditionError: Mismatched ALLREDUCE CPU/GPU device selection`  problem by  #398 . The system of the machines is `CentOS Linux release 7.5.1804 (Core) `.
I will show you more info to help me to locate the problem. 
```
yanghang ml3<~/temp_code/malconv-keras>$mpirun --prefix /usr/local -np 4 -H machine_A:2,machine_C:2 -bind-to none -map-by slot -x NCCL_DEBUG=ERROR -x NCCL_IB_DISABLE=1 -x LD_LIBRARY_PATH -x PATH -tag-output -mca pml ob1 -mca btl ^openib python /home/yanghang/horovod/examples/keras_mnist_advanced.py
[1,2]<stderr>:2018-12-04 14:04:44.335230: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[1,3]<stderr>:2018-12-04 14:04:44.335230: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[1,1]<stderr>:2018-12-04 14:04:44.325257: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[1,0]<stderr>:2018-12-04 14:04:44.325469: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[1,1]<stderr>:2018-12-04 14:04:44.601462: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[1,1]<stderr>:2018-12-04 14:04:44.602168: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
[1,1]<stderr>:name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6325
[1,1]<stderr>:pciBusID: 0000:02:00.0
[1,1]<stderr>:totalMemory: 10.92GiB freeMemory: 10.76GiB
[1,1]<stderr>:2018-12-04 14:04:44.602196: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 1
[1,0]<stderr>:2018-12-04 14:04:44.602343: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[1,0]<stderr>:2018-12-04 14:04:44.607166: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
[1,0]<stderr>:name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6325
[1,0]<stderr>:pciBusID: 0000:01:00.0
[1,0]<stderr>:totalMemory: 10.91GiB freeMemory: 10.76GiB
[1,0]<stderr>:2018-12-04 14:04:44.607354: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
[1,1]<stderr>:2018-12-04 14:04:45.155870: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
[1,1]<stderr>:2018-12-04 14:04:45.155903: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      1 
[1,1]<stderr>:2018-12-04 14:04:45.155909: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 1:   N 
[1,1]<stderr>:2018-12-04 14:04:45.156059: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10396 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
[1,0]<stderr>:2018-12-04 14:04:45.183446: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
[1,0]<stderr>:2018-12-04 14:04:45.183527: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
[1,0]<stderr>:2018-12-04 14:04:45.183561: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
[1,0]<stderr>:2018-12-04 14:04:45.183791: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10394 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
[1,0]<stdout>:x_train shape: (60000, 28, 28, 1)
[1,0]<stdout>:60000 train samples
[1,0]<stdout>:10000 test samples
[1,1]<stdout>:x_train shape: (60000, 28, 28, 1)
[1,1]<stdout>:60000 train samples
[1,1]<stdout>:10000 test samples
[1,0]<stderr>:Using TensorFlow backend.
[1,0]<stderr>:WARNING:tensorflow:From /home/yanghang/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:1259: calling reduce_prod (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
[1,0]<stderr>:Instructions for updating:
[1,0]<stderr>:keep_dims is deprecated, use keepdims instead
[1,1]<stderr>:Using TensorFlow backend.
[1,1]<stderr>:WARNING:tensorflow:From /home/yanghang/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:1259: calling reduce_prod (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
[1,1]<stderr>:Instructions for updating:
[1,1]<stderr>:keep_dims is deprecated, use keepdims instead
[1,3]<stderr>:2018-12-04 14:04:45.867051: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
[1,3]<stderr>:name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
[1,3]<stderr>:pciBusID: 0000:04:00.0
[1,3]<stderr>:totalMemory: 10.92GiB freeMemory: 10.76GiB
[1,3]<stderr>:2018-12-04 14:04:45.867116: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 1
[1,2]<stderr>:2018-12-04 14:04:45.874434: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
[1,2]<stderr>:name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
[1,2]<stderr>:pciBusID: 0000:03:00.0
[1,2]<stderr>:totalMemory: 10.92GiB freeMemory: 10.76GiB
[1,2]<stderr>:2018-12-04 14:04:45.874471: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
[1,1]<stderr>:WARNING:tensorflow:From /home/yanghang/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:2880: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
[1,1]<stderr>:Instructions for updating:
[1,1]<stderr>:keep_dims is deprecated, use keepdims instead
[1,1]<stderr>:WARNING:tensorflow:From /home/yanghang/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:1344: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
[1,1]<stderr>:Instructions for updating:
[1,1]<stderr>:keep_dims is deprecated, use keepdims instead
[1,0]<stderr>:WARNING:tensorflow:From /home/yanghang/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:2880: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
[1,0]<stderr>:Instructions for updating:
[1,0]<stderr>:keep_dims is deprecated, use keepdims instead
[1,0]<stderr>:WARNING:tensorflow:From /home/yanghang/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:1344: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
[1,0]<stderr>:Instructions for updating:
[1,0]<stderr>:keep_dims is deprecated, use keepdims instead
[1,3]<stderr>:2018-12-04 14:04:46.211548: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
[1,3]<stderr>:2018-12-04 14:04:46.211600: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      1 
[1,3]<stderr>:2018-12-04 14:04:46.211609: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 1:   N 
[1,3]<stderr>:2018-12-04 14:04:46.211933: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10405 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:04:00.0, compute capability: 6.1)
[1,2]<stderr>:2018-12-04 14:04:46.217991: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
[1,2]<stderr>:2018-12-04 14:04:46.218025: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
[1,2]<stderr>:2018-12-04 14:04:46.218045: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
[1,2]<stderr>:2018-12-04 14:04:46.218355: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10405 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
[1,2]<stdout>:x_train shape: (60000, 28, 28, 1)
[1,2]<stdout>:60000 train samples
[1,2]<stdout>:10000 test samples
[1,3]<stdout>:x_train shape: (60000, 28, 28, 1)
[1,3]<stdout>:60000 train samples
[1,3]<stdout>:10000 test samples
[1,1]<stdout>:Epoch 1/24
[1,2]<stdout>:Epoch 1/24
[1,3]<stdout>:Epoch 1/24
[1,0]<stdout>:Epoch 1/24
[1,2]<stderr>:Using TensorFlow backend.
[1,3]<stderr>:Using TensorFlow backend.
[1,2]<stderr>:Traceback (most recent call last):
[1,2]<stderr>:  File "/home/yanghang/horovod/examples/keras_mnist_advanced.py", line 122, in <module>
[1,2]<stderr>:    validation_steps=3 * test_batches // hvd.size())
[1,2]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
[1,2]<stderr>:    return func(*args, **kwargs)
[1,2]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 1418, in fit_generator
[1,2]<stderr>:    initial_epoch=initial_epoch)
[1,2]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
[1,2]<stderr>:    class_weight=class_weight)
[1,2]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 1217, in train_on_batch
[1,2]<stderr>:    outputs = self.train_function(ins)
[1,2]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
[1,2]<stderr>:    return self._call(inputs)
[1,2]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
[1,2]<stderr>:    fetched = self._callable_fn(*array_vals)
[1,2]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
[1,2]<stderr>:    run_metadata_ptr)
[1,2]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
[1,2]<stderr>:    c_api.TF_GetCode(self.status.status))
[1,2]<stderr>:tensorflow.python.framework.errors_impl.FailedPreconditionError: Mismatched ALLREDUCE CPU/GPU device selection: One rank specified device CPU, but another rank specified device GPU.
[1,2]<stderr>:	 [[{{node training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_dense_2_MatMul_grad_MatMul_1_0}} = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](training/Adadelta/gradients/dense_2/MatMul_grad/MatMul_1/_229)]]
[1,2]<stderr>:	 [[{{node training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_conv2d_2_convolution_grad_Conv2DBackpropFilter_0/_249}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_621_t...opFilter_0", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
[1,3]<stderr>:Traceback (most recent call last):
[1,3]<stderr>:  File "/home/yanghang/horovod/examples/keras_mnist_advanced.py", line 122, in <module>
[1,3]<stderr>:    validation_steps=3 * test_batches // hvd.size())
[1,3]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
[1,3]<stderr>:    return func(*args, **kwargs)
[1,3]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 1418, in fit_generator
[1,3]<stderr>:    initial_epoch=initial_epoch)
[1,3]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
[1,3]<stderr>:    class_weight=class_weight)
[1,3]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 1217, in train_on_batch
[1,3]<stderr>:    outputs = self.train_function(ins)
[1,3]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
[1,3]<stderr>:    return self._call(inputs)
[1,3]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
[1,3]<stderr>:    fetched = self._callable_fn(*array_vals)
[1,3]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
[1,3]<stderr>:    run_metadata_ptr)
[1,3]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
[1,3]<stderr>:    c_api.TF_GetCode(self.status.status))
[1,3]<stderr>:tensorflow.python.framework.errors_impl.FailedPreconditionError: Mismatched ALLREDUCE CPU/GPU device selection: One rank specified device CPU, but another rank specified device GPU.
[1,3]<stderr>:	 [[{{node training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_dense_2_MatMul_grad_MatMul_1_0}} = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](training/Adadelta/gradients/dense_2/MatMul_grad/MatMul_1/_229)]]
[1,3]<stderr>:	 [[{{node training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_conv2d_2_convolution_grad_Conv2DBackpropFilter_0/_249}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_621_t...opFilter_0", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
[1,0]<stderr>:    return fn(*args)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
[1,0]<stderr>:    options, feed_dict, fetch_list, target_list, run_metadata)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
[1,0]<stderr>:    run_metadata)
[1,0]<stderr>:tensorflow.python.framework.errors_impl.FailedPreconditionError: Mismatched ALLREDUCE CPU/GPU device selection: One rank specified device CPU, but another rank specified device GPU.
[1,0]<stderr>:	 [[{{node training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_dense_2_MatMul_grad_MatMul_1_0}} = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adadelta/gradients/dense_2/MatMul_grad/MatMul_1)]]
[1,0]<stderr>:
[1,0]<stderr>:During handling of the above exception, another exception occurred:
[1,0]<stderr>:
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "/home/yanghang/horovod/examples/keras_mnist_advanced.py", line 122, in <module>
[1,0]<stderr>:    validation_steps=3 * test_batches // hvd.size())
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
[1,0]<stderr>:    return func(*args, **kwargs)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/models.py", line 1223, in fit_generator
[1,0]<stderr>:    initial_epoch=initial_epoch)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
[1,0]<stderr>:    return func(*args, **kwargs)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 2096, in fit_generator
[1,0]<stderr>:    class_weight=class_weight)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 1814, in train_on_batch
[1,0]<stderr>:    outputs = self.train_function(ins)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2352, in __call__
[1,0]<stderr>:    **self.session_kwargs)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
[1,0]<stderr>:    run_metadata_ptr)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _run
[1,0]<stderr>:    feed_dict_tensor, options, run_metadata)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
[1,0]<stderr>:    run_metadata)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
[1,0]<stderr>:    raise type(e)(node_def, op, message)
[1,0]<stderr>:tensorflow.python.framework.errors_impl.FailedPreconditionError: Mismatched ALLREDUCE CPU/GPU device selection: One rank specified device CPU, but another rank specified device GPU.
[1,0]<stderr>:	 [[node training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_dense_2_MatMul_grad_MatMul_1_0 (defined at <string>:51)  = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adadelta/gradients/dense_2/MatMul_grad/MatMul_1)]]
[1,0]<stderr>:
[1,0]<stderr>:Caused by op 'training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_dense_2_MatMul_grad_MatMul_1_0', defined at:
[1,0]<stderr>:  File "/home/yanghang/horovod/examples/keras_mnist_advanced.py", line 122, in <module>
[1,0]<stderr>:    validation_steps=3 * test_batches // hvd.size())
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
[1,0]<stderr>:    return func(*args, **kwargs)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/models.py", line 1223, in fit_generator
[1,0]<stderr>:    initial_epoch=initial_epoch)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
[1,0]<stderr>:    return func(*args, **kwargs)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 1978, in fit_generator
[1,0]<stderr>:    self._make_train_function()
[1,0]<stderr>:  File "/home/yanghang/anaconda3/l[1,0]<stderr>:ib/python3.5/site-packages/keras/engine/training.py", line 990, in _make_train_function
[1,0]<stderr>:    loss=self.total_loss)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
[1,0]<stderr>:    return func(*args, **kwargs)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/optimizers.py", line 344, in get_updates
[1,0]<stderr>:    grads = self.get_gradients(loss, params)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/horovod/_keras/__init__.py", line 55, in get_gradients
[1,0]<stderr>:    compression=self._compression)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/horovod/tensorflow/__init__.py", line 83, in allreduce
[1,0]<stderr>:    summed_tensor_compressed = _allreduce(tensor_compressed)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/horovod/tensorflow/mpi_ops.py", line 90, in _allreduce
[1,0]<stderr>:    return MPI_LIB.horovod_allreduce(tensor, name=name)
[1,0]<stderr>:  File "<string>", line 51, in horovod_allreduce
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
[1,0]<stderr>:    op_def=op_def)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
[1,0]<stderr>:    return func(*args, **kwargs)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
[1,0]<stderr>:    op_def=op_def)
[1,0]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
[1,0]<stderr>:    self._traceback = tf_stack.extract_stack()
[1,0]<stderr>:
[1,0]<stderr>:FailedPreconditionError (see above for traceback): Mismatched ALLREDUCE CPU/GPU device selection: One rank specified device CPU, but another rank specified device GPU.
[1,0]<stderr>:	 [[node training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_dense_2_MatMul_grad_MatMul_1_0 (defined at <string>:51)  = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adadelta/gradients/dense_2/MatMul_grad/MatMul_1)]]
[1,0]<stderr>:
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
[1,1]<stderr>:    return fn(*args)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
[1,1]<stderr>:    options, feed_dict, fetch_list, target_list, run_metadata)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
[1,1]<stderr>:    run_metadata)
[1,1]<stderr>:tensorflow.python.framework.errors_impl.FailedPreconditionError: Mismatched ALLREDUCE CPU/GPU device selection: One rank specified device CPU, but another rank specified device GPU.
[1,1]<stderr>:	 [[{{node training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_dense_2_MatMul_grad_MatMul_1_0}} = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adadelta/gradients/dense_2/MatMul_grad/MatMul_1)]]
[1,1]<stderr>:
[1,1]<stderr>:During handling of the above exception, another exception occurred:
[1,1]<stderr>:
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "/home/yanghang/horovod/examples/keras_mnist_advanced.py", line 122, in <module>
[1,1]<stderr>:    validation_steps=3 * test_batches // hvd.size())
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
[1,1]<stderr>:    return func(*args, **kwargs)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/models.py", line 1223, in fit_generator
[1,1]<stderr>:    initial_epoch=initial_epoch)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
[1,1]<stderr>:    return func(*args, **kwargs)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 2096, in fit_generator
[1,1]<stderr>:    class_weight=class_weight)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 1814, in train_on_batch
[1,1]<stderr>:    outputs = self.train_function(ins)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2352, in __call__
[1,1]<stderr>:    **self.session_kwargs)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
[1,1]<stderr>:    run_metadata_ptr)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _run
[1,1]<stderr>:    feed_dict_tensor, options, run_metadata)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
[1,1]<stderr>:    run_metadata)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
[1,1]<stderr>:    raise type(e)(node_def, op, message)
[1,1]<stderr>:tensorflow.python.framework.errors_impl.FailedPreconditionError: Mismatched ALLREDUCE CPU/GPU device selection: One rank specified device CPU, but another rank specified device GPU.
[1,1]<stderr>:	 [[node training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_dense_2_MatMul_grad_MatMul_1_0 (defined at <string>:51)  = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adadelta/gradients/dense_2/MatMul_grad/MatMul_1)]]
[1,1]<stderr>:
[1,1]<stderr>:Caused by op 'training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_dense_2_MatMul_grad_MatMul_1_0', defined at:
[1,1]<stderr>:  File "/home/yanghang/horovod/examples/keras_mnist_advanced.py", line 122, in <module>
[1,1]<stderr>:    validation_steps=3 * test_batches // hvd.size())
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
[1,1]<stderr>:    return func(*args, **kwargs)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/models.py", line 1223, in fit_generator
[1,1]<stderr>:    initial_epoch=initial_epoch)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
[1,1]<stderr>:    return func(*args, **kwargs)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 1978, in fit_generator
[1,1]<stderr>:    self._make_train_function()
[1,1]<stderr>:  File "/home/yanghang/anaconda3/l[1,1]<stderr>:ib/python3.5/site-packages/keras/engine/training.py", line 990, in _make_train_function
[1,1]<stderr>:    loss=self.total_loss)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
[1,1]<stderr>:    return func(*args, **kwargs)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/keras/optimizers.py", line 344, in get_updates
[1,1]<stderr>:    grads = self.get_gradients(loss, params)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/horovod/_keras/__init__.py", line 55, in get_gradients
[1,1]<stderr>:    compression=self._compression)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/horovod/tensorflow/__init__.py", line 83, in allreduce
[1,1]<stderr>:    summed_tensor_compressed = _allreduce(tensor_compressed)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/horovod/tensorflow/mpi_ops.py", line 90, in _allreduce
[1,1]<stderr>:    return MPI_LIB.horovod_allreduce(tensor, name=name)
[1,1]<stderr>:  File "<string>", line 51, in horovod_allreduce
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
[1,1]<stderr>:    op_def=op_def)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
[1,1]<stderr>:    return func(*args, **kwargs)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
[1,1]<stderr>:    op_def=op_def)
[1,1]<stderr>:  File "/home/yanghang/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
[1,1]<stderr>:    self._traceback = tf_stack.extract_stack()
[1,1]<stderr>:
[1,1]<stderr>:FailedPreconditionError (see above for traceback): Mismatched ALLREDUCE CPU/GPU device selection: One rank specified device CPU, but another rank specified device GPU.
[1,1]<stderr>:	 [[node training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_dense_2_MatMul_grad_MatMul_1_0 (defined at <string>:51)  = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adadelta/gradients/dense_2/MatMul_grad/MatMul_1)]]
[1,1]<stderr>:
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[35048,1],2]
  Exit code:    1
--------------------------------------------------------------------------

```

**Comment by Yang-HangWA** [comment]
In addition to this, I agree with you there is a bug in my training script. So how can I locate the problem.
My code is as follow:
```
from os.path import join
import argparse
import pickle
import warnings
import pandas as pd
from keras.callbacks import ModelCheckpoint, EarlyStopping
from keras.models import load_model
import utils
from preprocess import preprocess
from keras.callbacks import TensorBoard
from model_file import model_x
import datetime
import os
from keras import optimizers
import tensorflow as tf
import horovod.keras as hvd
import math
from keras import backend as K
import keras

#initialize
hvd.init()
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
config.gpu_options.visible_device_list = str(hvd.local_rank())
K.set_session(tf.Session(config=config))
warnings.filterwarnings("ignore")

epochs = 12

parser = argparse.ArgumentParser(description='Horovod-keras test training')
parser.add_argument('--batch_size', type=int, default=64)
#parser.add_argument('--epochs', type=int, default=10)
parser.add_argument('--limit', type=float, default=0., help="limit gpy memory percentage")
parser.add_argument('--max_len', type=int, default=200000, help="model input legnth")
parser.add_argument('--val_size', type=float, default=0.1, help="validation percentage")
parser.add_argument('--save_path', type=str, default='./saved/', help='Directory to save model and log')
parser.add_argument('--model_path', type=str, default='./saved/malconv.h5', help="model to resume")
parser.add_argument('--model_type',type=int,default=2,help="To decide the model number")
parser.add_argument('--resume',type=int,default=0,help="Retrain or continue last model parm")
parser.add_argument('csv', type=str)

args = parser.parse_args()




if __name__ == '__main__':
    save_best = True
    verbose = True
    batch_size = args.batch_size
    max_len = args.max_len
    save_path = args.save_path
    args = parser.parse_args()
     
    # prepare model resume=1 continue to train the model
    if args.resume==1:
        model = load_model(args.model_path)
        print("=============load model!===============")
    else:
	    model = model_x(args.max_len)
        # Horovod: adjust learning rate based on number of GPUs.
        opt = keras.optimizers.Adadelta(1.0 * hvd.size())
        # Horovod: add Horovod Distributed Optimizer.
        opt = hvd.DistributedOptimizer(opt)
        model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['acc'])
        
    model.summary()
    # prepare data
    # preprocess is handled in utils.data_generator
    df = pd.read_csv(args.csv, header=None)
    data, label = df[0].values, df[1].values
    
    x_train, x_test, y_train, y_test = utils.train_test_split(data, label, args.val_size)
    print('Train on %d data, test on %d data' % (len(x_train), len(x_test)))
    
    callbacks_list= [
    hvd.callbacks.BroadcastGlobalVariablesCallback(0),
    hvd.callbacks.MetricAverageCallback(),
    hvd.callbacks.LearningRateWarmupCallback(warmup_epochs=5, verbose=1),
    keras.callbacks.ReduceLROnPlateau(patience=10, verbose=1),
    ]    
 
    history = model.fit_generator(
        utils.data_generator(x_train, y_train, max_len, batch_size, shuffle=True),
        steps_per_epoch=len(x_train)//batch_size + 1,
        epochs=epochs,
        verbose=verbose,
        callbacks=callbacks_list,
        validation_data=utils.data_generator(x_test, y_test, max_len, batch_size),
        validation_steps=len(x_test)//batch_size + 1)
		
    # Horovod: save checkpoints only on worker 0 to prevent other workers from corrupting them.
    if hvd.rank()==0:
        callbacks_list.append(keras.callbacks.ModelCheckpoint('./checkpoint-{epoch}.h5'))
    
    
    with open(join(args.save_path, 'history.pkl'), 'wb') as f:
        pickle.dump(history.history, f)
```

**Comment by Yang-HangWA** [comment]
When I run keras_minst_advanced.py on machine B and machine C. It seems work fine at first.But after a epoch,there appears a warning as follow:
```
yanghang ml2<~>$mpirun -np 4 -H 10.91.42.95:2,10.91.42.19:2 -bind-to none -map-by slot -x NCCL_DEBUG=ERROR -x NCCL_IB_DISABLE=1 -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python /home/yanghang/horovod/examples/keras_mnist_advanced.py
2018-12-04 16:51:26.444622: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-12-04 16:51:26.444800: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-12-04 16:51:26.448097: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-12-04 16:51:26.448081: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-12-04 16:51:26.651945: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-12-04 16:51:26.652044: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-12-04 16:51:26.652835: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:02:00.0
totalMemory: 10.92GiB freeMemory: 10.76GiB
2018-12-04 16:51:26.652850: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 1
2018-12-04 16:51:26.652928: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6325
pciBusID: 0000:01:00.0
totalMemory: 10.91GiB freeMemory: 10.76GiB
2018-12-04 16:51:26.652942: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2018-12-04 16:51:26.873967: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-04 16:51:26.873993: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      1 
2018-12-04 16:51:26.873999: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 1:   N 
2018-12-04 16:51:26.874192: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10405 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
2018-12-04 16:51:26.876554: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-04 16:51:26.876571: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2018-12-04 16:51:26.876576: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2018-12-04 16:51:26.876748: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10403 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
Using TensorFlow backend.
WARNING:tensorflow:From /home/yanghang/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:1259: calling reduce_prod (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Using TensorFlow backend.
WARNING:tensorflow:From /home/yanghang/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:1259: calling reduce_prod (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/yanghang/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:2880: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/yanghang/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:2880: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/yanghang/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:1344: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/yanghang/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:1344: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2018-12-04 16:51:27.975713: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:03:00.0
totalMemory: 10.92GiB freeMemory: 10.76GiB
2018-12-04 16:51:27.975751: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2018-12-04 16:51:27.996647: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:04:00.0
117/117 [==============================] - 13s 114ms/step - loss: 0.9619 - acc: 0.6975 - val_loss: 0.1307 - val_acc: 0.9580TA: 0s - loss: 1.1746 - acc: 0.6598
113/117 [===========================>..] - ETA: 0s - loss: 0.9863 - acc: 0.6874112/117 [===========================>..] - ETA: 0s - loss: 1.1852 - acc: 0.6563
111/117 [===========================>..] - ETA: 0s - loss: 0.9955 - acc: 0.6845106/117 [==========================>...] - ETA: 1s - loss: 1.2205 - acc: 0.6456
105/117 [=========================>....] - ETA: 1s - loss: 1.0238 - acc: 0.6741 97/117 [=======================>......] - ETA: 2s - loss: 1.0649 - acc: 0.6594
 97/117 [=======================>......] - ETA: 2s - loss: 1.2739 - acc: 0.6280 86/117 [=====================>........] - ETA: 3s - loss: 1.1407 - acc: 0.6345
 86/117 [=====================>........] - ETA: 3s - loss: 1.3545 - acc: 0.6021 85/117 [====================>.........] - ETA: 3s - loss: 1.1351 - acc: 0.6375ith 10405 MB memory) -> 85/117 [====================>.........] - ETA: 3s - loss: 1.3595 - acc: 0.6006 78/117 [===================>..........] - ETA: 4s - loss: 1.4040 - acc: 0.5874
 77/117 [==================>...........] - ETA: 4s - loss: 1.2078 - acc: 0.6116 62/117 [==============>...............] - ETA: 6s - loss: 1.3134 - acc: 0.5770
 61/117 [==============>...............] - ETA: 6s - loss: 1.3242 - acc: 0.5729 61/117 [==============>...............] - ETA: 6s - loss: 1.5436 - acc: 0.5420
 60/117 [==============>...............] - ETA: 7s - loss: 1.3683 - acc: 0.5566 60/117 [==============>...............] - ETA: 7s - loss: 1.5482 - acc: 0.5422
 60/117 [==============>...............] - ETA: 7s - loss: 1.3355 - acc: 0.5687 56/117 [=============>................] - ETA: 7s - loss: 1.4147 - acc: 0.5419ith 10405 MB memory) -> 56/117 [=============>................] - ETA: 7s - loss: 1.5897 - acc: 0.5251 56/117 [=============>................] - ETA: 7s - loss: 1.5901 - acc: 0.5265
 55/117 [=============>................] - ETA: 7s - loss: 1.4197 - acc: 0.5409 55/117 [=============>................] - ETA: 7s - loss: 1.3889 - acc: 0.5509
 55/117 [=============>................] - ETA: 7s - loss: 1.5966 - acc: 0.5223 54/117 [============>.................] - ETA: 8s - loss: 1.6052 - acc: 0.5198
 54/117 [============>.................] - ETA: 8s - loss: 1.3881 - acc: 0.5502 53/117 [============>.................] - ETA: 8s - loss: 1.4268 - acc: 0.5361
 53/117 [============>.................] - ETA: 8s - loss: 1.6150 - acc: 0.5158 52/117 [============>.................] - ETA: 8s - loss: 1.4059 - acc: 0.5439
 52/117 [============>.................] - ETA: 8s - loss: 1.6261 - acc: 0.5116 47/117 [===========>..................] - ETA: 9s - loss: 1.6828 - acc: 0.4899
 47/117 [===========>..................] - ETA: 9s - loss: 1.4647 - acc: 0.5231 45/117 [==========>...................] - ETA: 9s - loss: 1.7018 - acc: 0.4823
 44/117 [==========>...................] - ETA: 9s - loss: 1.5389 - acc: 0.4977 44/117 [==========>...................] - ETA: 9s - loss: 1.7149 - acc: 0.4762
 43/117 [==========>...................] - ETA: 9s - loss: 1.5528 - acc: 0.4927  27/117 [=====>........................] - ETA: 13s - loss: 1.7220 - acc: 0.4285
 26/117 [=====>........................] - ETA: 14s - loss: 1.7740 - acc: 0.4050  6/117 [>.............................] - ETA: 38s - loss: 2.1762 - acc: 0.2109
  6/117 [>.............................] - ETA: 38s - loss: 2.2277 - acc: 0.1784  5/117 [>.............................] - ETA: 44s - loss: 2.1958 - acc: 0.2062
  5/117 [>.............................] - ETA: 44s - loss: 2.2410 - acc: 0.1688   1/117 [..............................] - ETA: 3:03 - loss: 2.3027 - acc: 0.0938









WARNING: One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
Stalled ops:
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_conv2d_1_BiasAdd_grad_BiasAddGrad_0 [missing ranks: 2, 3]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_conv2d_1_convolution_grad_Conv2DBackpropFilter_0 [missing ranks: 2, 3]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_conv2d_2_BiasAdd_grad_BiasAddGrad_0 [missing ranks: 2, 3]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_conv2d_2_convolution_grad_Conv2DBackpropFilter_0 [missing ranks: 2, 3]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_dense_1_BiasAdd_grad_BiasAddGrad_0 [missing ranks: 2, 3]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_dense_1_MatMul_grad_MatMul_1_0 [missing ranks: 2, 3]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_dense_2_BiasAdd_grad_BiasAddGrad_0 [missing ranks: 2, 3]
training/Adadelta/DistributedAdadelta_Allreduce/HorovodAllreduce_training_Adadelta_gradients_dense_2_MatMul_grad_MatMul_1_0 [missing ranks: 2, 3]
WARNING: One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 

```

**Comment by Yang-HangWA** [comment]
@tgaddair  Accidentally, I run the keras_mnist_advanced.py on machine B and machine C successful.However,I was confused that every epoch of training on four gpus is slower than training on one gpu and the training result is little difference.I looked #508. Does it matter to  your example ? Or I can get better result if I change another program. Beside, I change the nvidia drive of machine A and the problem is still there.

**Comment by Yang-HangWA** [comment]
I solve the  ` Mismatched ALLREDUCE CPU/GPU device selection: One rank specified device GPU, but another rank specified device CPU.`  problem by read https://github.com/uber/horovod/blob/master/docs/gpus.md. So I use `HOROVOD_NCCL_HOME=/usr/local/nccl-<version> HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod` to reinstall horovod. Now，the only problem is find the bug in my script.
