### ISSUE TITLE
NCCL connect timeout : Connection refused error 

### ISSUE THREAD

**Issue by crab1234** [uber/horovod#789]
Hello!
I'm using horovod on 2 dockers from 2 servers. But at last I meet an error and get stuck.
This is the error log:
`e53b7da88fea:2493:2753 [0] misc/ibvwrap.cu:63 NCCL WARN Failed to open libibverbs.so[.1]
e53b7da88fea:2493:2753 [0] NCCL INFO Using internal Network Socket
e53b7da88fea:2493:2753 [0] NCCL INFO NET : Using interface lo:127.0.0.1<0>
e53b7da88fea:2493:2753 [0] NCCL INFO NET : Using interface eth0:3.10.11.7<0>
e53b7da88fea:2493:2753 [0] NCCL INFO NET/Socket : 2 interfaces found
NCCL version 2.3.5+cuda9.0
e53b7da88fea:2493:2753 [0] NCCL INFO rank 0 nranks 4

e53b7da88fea:2494:2756 [1] misc/ibvwrap.cu:63 NCCL WARN Failed to open libibverbs.so[.1]
e53b7da88fea:2494:2756 [1] NCCL INFO Using internal Network Socket
e53b7da88fea:2494:2756 [1] NCCL INFO rank 1 nranks 4

51ca79e04561:4880:5140 [1] misc/ibvwrap.cu:63 NCCL WARN Failed to open libibverbs.so[.1]
51ca79e04561:4880:5140 [1] NCCL INFO Using internal Network Socket
51ca79e04561:4880:5140 [1] NCCL INFO rank 3 nranks 4

51ca79e04561:4879:5139 [0] misc/ibvwrap.cu:63 NCCL WARN Failed to open libibverbs.so[.1]
51ca79e04561:4879:5139 [0] NCCL INFO Using internal Network Socket
51ca79e04561:4879:5139 [0] NCCL INFO rank 2 nranks 4
Unexpected end of /proc/mounts line `overlay / overlay rw,seclabel,relatime,lowerdir=/var/lib/docker/overlay2/l/ZYU43OX3CISNABHGFCHFSTFUK4:/var/lib/docker/overlay2/l/3IYKLT4FOYWYRAD36E6FLWLQPA:/var/lib/docker/overlay2/l/B5WBTDSZMLKJECJ5T2QRAOFDUS:/var/lib/docker/overlay2/l/T5YYRFLRUD7FO6WVLXV4ITRX7H:/var/lib/docker/overlay2/l/J4AMZVT3YPERPWDCLUDCPHMHC2:/var/lib/docker/overlay2/l/JH4V2OFNLF6BJ72GKEOFSWAJR3:/var/lib/docker/overlay2/l/JRFRJNZT65Y4JOR2KSJCLTXM7J:/var/lib/docker/overlay2/l/K4CHB5LGRTY4KG3Q4VHOBZJLOP:/var/lib/docker/overlay2/l/GFTN'
Unexpected end of /proc/mounts line `BYGCFCIHYNRA33T6VITYU7:/var/lib/docker/overlay2/l/WVUBEIII6AZY6HII4FZKXXQKHT:/var/lib/docker/overlay2/l/66324QFIWKSDL34IVRM4WM64T3:/var/lib/docker/overlay2/l/ZA5OJLSHC4P2OG73GXKLYS3IOL:/var/lib/docker/overlay2/l/GY5SGNY7MSRFCWK5K6T2T6LOPQ:/var/lib/docker/overlay2/l/7CTPXIUSTTQMCTV4P23X3MU65Q:/var/lib/docker/overlay2/l/SFNEANWICFWHBBW7HQNHXIUMC5:/var/lib/docker/overlay2/l/NR5ALMDBAGN74L32CVDZA6CLJC:/var/lib/docker/overlay2/l/B4TJ7HUSAQ62YUKBEL3ME2J3L4:/var/lib/docker/overlay2/l/C7IRHAZ47YNZM2EIOYPT7YYA5I:/v'
Unexpected end of /proc/mounts line `overlay / overlay rw,seclabel,relatime,lowerdir=/var/lib/docker/overlay2/l/ZYU43OX3CISNABHGFCHFSTFUK4:/var/lib/docker/overlay2/l/3IYKLT4FOYWYRAD36E6FLWLQPA:/var/lib/docker/overlay2/l/B5WBTDSZMLKJECJ5T2QRAOFDUS:/var/lib/docker/overlay2/l/T5YYRFLRUD7FO6WVLXV4ITRX7H:/var/lib/docker/overlay2/l/J4AMZVT3YPERPWDCLUDCPHMHC2:/var/lib/docker/overlay2/l/JH4V2OFNLF6BJ72GKEOFSWAJR3:/var/lib/docker/overlay2/l/JRFRJNZT65Y4JOR2KSJCLTXM7J:/var/lib/docker/overlay2/l/K4CHB5LGRTY4KG3Q4VHOBZJLOP:/var/lib/docker/overlay2/l/GFTN'
Unexpected end of /proc/mounts line `BYGCFCIHYNRA33T6VITYU7:/var/lib/docker/overlay2/l/WVUBEIII6AZY6HII4FZKXXQKHT:/var/lib/docker/overlay2/l/66324QFIWKSDL34IVRM4WM64T3:/var/lib/docker/overlay2/l/ZA5OJLSHC4P2OG73GXKLYS3IOL:/var/lib/docker/overlay2/l/GY5SGNY7MSRFCWK5K6T2T6LOPQ:/var/lib/docker/overlay2/l/7CTPXIUSTTQMCTV4P23X3MU65Q:/var/lib/docker/overlay2/l/SFNEANWICFWHBBW7HQNHXIUMC5:/var/lib/docker/overlay2/l/NR5ALMDBAGN74L32CVDZA6CLJC:/var/lib/docker/overlay2/l/B4TJ7HUSAQ62YUKBEL3ME2J3L4:/var/lib/docker/overlay2/l/C7IRHAZ47YNZM2EIOYPT7YYA5I:/v'
Unexpected end of /proc/mounts line `overlay / overlay rw,seclabel,relatime,lowerdir=/var/lib/docker/overlay2/l/SCKVFCM3PCIDJZ7E3U4TA2726B:/var/lib/docker/overlay2/l/6E73LBIHCDXSL54DRVEAMY7BRG:/var/lib/docker/overlay2/l/67PTPXNAFS2C3J4BVYD3OH6JZY:/var/lib/docker/overlay2/l/4PEW3HGUQXB42BAGFGGPNAJPZF:/var/lib/docker/overlay2/l/NRROREW7DMTSTGYS2ZTOQAP5WS:/var/lib/docker/overlay2/l/CMGQAG3ELSPLAPVACFDA46R43T:/var/lib/docker/overlay2/l/A45AUUYJIW5QW54LXJY7XBIZ43:/var/lib/docker/overlay2/l/SGJQ2GBHAWNYZLQ46SEWJ3SSMM:/var/lib/docker/overlay2/l/OMHL'
Unexpected end of /proc/mounts line `LA3MI77RCXGVDKURZUGEEK:/var/lib/docker/overlay2/l/DRHACNEE4YE6OO24KB55JAL7CH:/var/lib/docker/overlay2/l/2453FWPFCMN4VG43QN3RWRHDWF:/var/lib/docker/overlay2/l/WYLUGBPGA3BMKCQOEGKO5QFTX7:/var/lib/docker/overlay2/l/AODLWLXVTYAVGHWB3F4MZYKSLK:/var/lib/docker/overlay2/l/VNUPM2YNKJUA2TAKKHNIEIYPBY:/var/lib/docker/overlay2/l/SR5XUWYHGNSJVU4XJ7AZIXFO6T:/var/lib/docker/overlay2/l/H2PRR5GPZIXKGKFLE6Z5G5VLYB:/var/lib/docker/overlay2/l/FKC64XJAUQCM4ZAROVLKWZ7DTF:/var/lib/docker/overlay2/l/WZE4DF45VJAZLS4S4ACHMOGVBR:/v'
Unexpected end of /proc/mounts line `ar/lib/docker/overlay2/l/CJH2WCBUMSSDTFGNSHKNF7C5FG:/var/lib/docker/overlay2/l/SUC4MGTVRTY22A3KRRJSUT6TG4:/var/lib/docker/overlay2/l/NII5BMFDZVNBE3LAEO7GHCF4OH:/var/lib/docker/overlay2/l/ERW7FBD64JVORI2NNHPL5IPKAJ:/var/lib/docker/overlay2/l/IZGFCSEX7MKT74O2O44XP24OAZ:/var/lib/docker/overlay2/l/2AY4I5ZQJWRQKITJ4NSOILUBSO,upperdir=/var/lib/docker/overlay2/9d1acc643d46860ec7037a35667c92c9d15cdfce5ea57cb0c70263575bc6d85a/diff,workdir=/var/lib/docker/overlay2/9d1acc643d46860ec7037a35667c92c9d15cdfce5ea57cb0c702'
Unexpected end of /proc/mounts line `overlay / overlay rw,seclabel,relatime,lowerdir=/var/lib/docker/overlay2/l/SCKVFCM3PCIDJZ7E3U4TA2726B:/var/lib/docker/overlay2/l/6E73LBIHCDXSL54DRVEAMY7BRG:/var/lib/docker/overlay2/l/67PTPXNAFS2C3J4BVYD3OH6JZY:/var/lib/docker/overlay2/l/4PEW3HGUQXB42BAGFGGPNAJPZF:/var/lib/docker/overlay2/l/NRROREW7DMTSTGYS2ZTOQAP5WS:/var/lib/docker/overlay2/l/CMGQAG3ELSPLAPVACFDA46R43T:/var/lib/docker/overlay2/l/A45AUUYJIW5QW54LXJY7XBIZ43:/var/lib/docker/overlay2/l/SGJQ2GBHAWNYZLQ46SEWJ3SSMM:/var/lib/docker/overlay2/l/OMHL'
Unexpected end of /proc/mounts line `LA3MI77RCXGVDKURZUGEEK:/var/lib/docker/overlay2/l/DRHACNEE4YE6OO24KB55JAL7CH:/var/lib/docker/overlay2/l/2453FWPFCMN4VG43QN3RWRHDWF:/var/lib/docker/overlay2/l/WYLUGBPGA3BMKCQOEGKO5QFTX7:/var/lib/docker/overlay2/l/AODLWLXVTYAVGHWB3F4MZYKSLK:/var/lib/docker/overlay2/l/VNUPM2YNKJUA2TAKKHNIEIYPBY:/var/lib/docker/overlay2/l/SR5XUWYHGNSJVU4XJ7AZIXFO6T:/var/lib/docker/overlay2/l/H2PRR5GPZIXKGKFLE6Z5G5VLYB:/var/lib/docker/overlay2/l/FKC64XJAUQCM4ZAROVLKWZ7DTF:/var/lib/docker/overlay2/l/WZE4DF45VJAZLS4S4ACHMOGVBR:/v'
Unexpected end of /proc/mounts line `ar/lib/docker/overlay2/l/CJH2WCBUMSSDTFGNSHKNF7C5FG:/var/lib/docker/overlay2/l/SUC4MGTVRTY22A3KRRJSUT6TG4:/var/lib/docker/overlay2/l/NII5BMFDZVNBE3LAEO7GHCF4OH:/var/lib/docker/overlay2/l/ERW7FBD64JVORI2NNHPL5IPKAJ:/var/lib/docker/overlay2/l/IZGFCSEX7MKT74O2O44XP24OAZ:/var/lib/docker/overlay2/l/2AY4I5ZQJWRQKITJ4NSOILUBSO,upperdir=/var/lib/docker/overlay2/9d1acc643d46860ec7037a35667c92c9d15cdfce5ea57cb0c70263575bc6d85a/diff,workdir=/var/lib/docker/overlay2/9d1acc643d46860ec7037a35667c92c9d15cdfce5ea57cb0c702'
51ca79e04561:4879:5139 [0] NCCL INFO comm 0x7f6cc0424dd0 rank 2 nranks 4
51ca79e04561:4879:5139 [0] NCCL INFO NET : Using interface lo:127.0.0.1<0>
51ca79e04561:4879:5139 [0] NCCL INFO NET : Using interface eth0:3.5.6.12<0>
51ca79e04561:4879:5139 [0] NCCL INFO NET/Socket : 2 interfaces found
51ca79e04561:4880:5140 [1] NCCL INFO comm 0x7f19bc4046d0 rank 3 nranks 4
51ca79e04561:4880:5140 [1] NCCL INFO NET : Using interface lo:127.0.0.1<0>
51ca79e04561:4880:5140 [1] NCCL INFO NET : Using interface eth0:3.5.6.12<0>
51ca79e04561:4880:5140 [1] NCCL INFO NET/Socket : 2 interfaces found
e53b7da88fea:2494:2756 [1] NCCL INFO comm 0x7f2bd8406d50 rank 1 nranks 4
e53b7da88fea:2494:2756 [1] NCCL INFO NET : Using interface lo:127.0.0.1<0>
e53b7da88fea:2494:2756 [1] NCCL INFO NET : Using interface eth0:3.10.11.7<0>
e53b7da88fea:2494:2756 [1] NCCL INFO NET/Socket : 2 interfaces found
e53b7da88fea:2493:2753 [0] NCCL INFO comm 0x7f4ee83b6bc0 rank 0 nranks 4
e53b7da88fea:2493:2753 [0] NCCL INFO Could not find real path of /sys/class/net/lo/device
e53b7da88fea:2493:2753 [0] NCCL INFO Could not find real path of /sys/class/net/eth0/device
e53b7da88fea:2493:2753 [0] NCCL INFO CUDA Dev 0, IP Interfaces : lo(SOC) eth0(SOC)
e53b7da88fea:2494:2756 [1] NCCL INFO Could not find real path of /sys/class/net/lo/device
e53b7da88fea:2494:2756 [1] NCCL INFO Could not find real path of /sys/class/net/eth0/device
e53b7da88fea:2494:2756 [1] NCCL INFO CUDA Dev 1, IP Interfaces : lo(SOC) eth0(SOC)

51ca79e04561:4880:5140 [1] include/socket.h:361 NCCL WARN Call to connect timeout : Connection refused
51ca79e04561:4880:5140 [1] NCCL INFO transport/net_socket.cu:139 -> 2
51ca79e04561:4880:5140 [1] NCCL INFO bootstrap.cu:19 -> 2
51ca79e04561:4880:5140 [1] NCCL INFO bootstrap.cu:225 -> 2
51ca79e04561:4880:5140 [1] NCCL INFO init.cu:420 -> 2
51ca79e04561:4880:5140 [1] NCCL INFO init.cu:557 -> 2`

this is my docker info:
master(server1):
nvidia-docker run -itd -v /mnt/ainfs/imagenet:/share --ip 3.10.11.7 --name xhorovod --network mydocker -e "CUDA_VISIBLE_DEVICES=6,7,8,9" horovod_resnet50:v2
worker(on server2):
nvidia-docker run -itd -v /mnt/ainfs/imagenet:/share --ip 3.5.6.12 --name xhorovod --network mydocker -e "CUDA_VISIBLE_DEVICES=6,7,8,9" horovod_resnet50:v2

##  --network mydocker   user-defined docker network, using macvlan driver.
detailed info:
server1
`[root@dayang4 ~]# docker inspect mydocker
[
    {
        "Name": "mydocker",
        "Id": "3643d83cb2ccb47c801ec7c56db7b4aea62ea8bb6796f48a4dfb4c10b86a1b20",
        "Created": "2019-01-23T16:46:00.179762766+08:00",
        "Scope": "local",
        "Driver": "macvlan",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "3.0.0.0/8",
                    "Gateway": "3.0.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "424030a00dc63e0a813d0676937df07151278f626ca0c6afd581a25dd3cf1d9c": {
                "Name": "zybhorovod",
                "EndpointID": "724fe282b683438a68117c367fc10f1462c5cf8f7ff60fd2c12c28d75327e8a6",
                "MacAddress": "02:42:03:0a:0b:06",
                "IPv4Address": "3.10.11.6/8",
                "IPv6Address": ""
            },
            "7dad637fbfacdd5dd839f42b01aa11c09ca2d8c11816f4b08bfa68ed43c79282": {
                "Name": "testwork",
                "EndpointID": "8b5b157c084d3ef737f063d78143134cdba26e56d49f1fc49f867569e434850c",
                "MacAddress": "02:42:03:03:01:0c",
                "IPv4Address": "3.3.1.12/8",
                "IPv6Address": ""
            },
            "e53b7da88feafde2d8dd3ede2f941f6ac139d9cf347c5f4d545d5d998c855408": {
                "Name": "xhorovod",
                "EndpointID": "a2d51bb337305e671026179508072b8163bacdd4228a620b997cd87f690066df",
                "MacAddress": "02:42:03:0a:0b:07",
                "IPv4Address": "3.10.11.7/8",
                "IPv6Address": ""
            }
        },
        "Options": {
            "parent": "enp24s0f0"
        },
        "Labels": {}
    }
]`

server2:
`    {
        "Name": "mydocker",
        "Id": "328cf2286f4733504b666b8c276f1e162f9751b368a3b4a12056591a69558bd6",
        "Created": "2019-01-23T16:51:45.139688555+08:00",
        "Scope": "local",
        "Driver": "macvlan",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "3.0.0.0/8",
                    "Gateway": "3.0.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "51ca79e0456177d1351de3fb5fd4425116f76b12423ac1c408018744d0b0e91e": {
                "Name": "zybhorovod",
                "EndpointID": "bbb7eeb7142e0502fc5e42e30a7d34c3ebff43b4cdb66c160d45dd6276703006",
                "MacAddress": "02:42:03:05:06:0c",
                "IPv4Address": "3.5.6.12/8",
                "IPv6Address": ""
            }
        },
        "Options": {
            "parent": "enp24s0"
        },
        "Labels": {}
    }
]
`
and finally my script:
master:
mpirun -np 4 -H 3.10.11.7:2,3.5.6.12:2 -bind-to none -map-by slot \
    -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -mca btl_tcp_if_exclude=docker0,enp24s0f1,flannel.1,lo,docker_gwbridge,enp24s0d1 NCCL_SOCKET_IFNAME=^docker0,enp24s0f1,flannel.1,lo,docker_gwbridge,enp24s0d1 \
    -mca pml ob1 -mca btl ^openib -mca plm_rsh_args "-p 12345"\
    python /share/keras_imagenet_resnet50.py --batch-size=16
worker:
bash -c "/usr/sbin/sshd -p 12345; sleep infinity"

Does anyone can help me about this?
thanks!

**Comment by crab1234** [comment]
I just solved the problem

**Comment by chrjxj** [comment]
@crab1234 hey, I got the same issue inside docker: `misc/ibvwrap.cu:63 NCCL WARN Failed to open libibverbs.so[.1]`. would you please help your solution? thanks a lot.

**Comment by petkovacs19** [comment]
> I just solved the problem

Can you share how you solved the problem?

**Comment by petkovacs19** [comment]
> I just solved the problem

@crab1234 Can you share how you solved the problem please?

**Comment by crab1234** [comment]
@chrjxj @petkovacs19 
Actually I just made a small problem.
In command line, before "NCCL_SOCKET_IFNAME=" I forgot to add "-X"
I add -X and it works well.

this is my new script:
mpirun -np 16 -H 3.10.11.8:8,3.10.22.8:8 -bind-to none -map-by slot \
    --output-filename /share/logs_resnet50 \
    -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -mca btl_tcp_if_exclude docker0,lo -x NCCL_SOCKET_IFNAME=^docker0,lo \
    -mca pml ob1 -mca btl ^openib -mca plm_rsh_args "-p 12345" \
    python /share/keras_imagenet_resnet50.py |& grep -v "Read -1"
